[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6375ebb90fc7ad28b0d6d61f495aa386f0896e3f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a194e00a28ff4243a60b0fd41db490dfa2a95ccff6079ff69b924cc93d90b9b9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6533148b2e4f5148791276f0b9d8f6848025e7bd"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "bb6d70c5fb6b6ee7b9b621d177619df32b43191d5fcd357f49da2bfafd3cd024"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a49a6e0b88e6b730a9d045a3ac3f10e9e57c1b79"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "573bc557fa4382c6e19b72bfde3893515f6fb3f93290ecef4a3d2606c118f06a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a8230f8ca566d1d80dcc93e6683cf3fe356c263"
os = "windows"

    [[PROJ.download]]
    sha256 = "e0be6a6f0f9066e14ae133e92b79182b0cd3d470a0cedb55a0e744619fd980f7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5874539792499b7a807145205b64887fcfd4ba63"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e1897a762b204a1d6ad063bc34e76fac9f225678d109252b2f6a184d99fab1f6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d39373ee6c9e7e766f0509ff5c4a0db10583df1e"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "342dd4eb5ee3600194bb3b103f8ffb53644cb4fce05aa524207e065683752ade"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38925531e08d47d345acc7b117c0e6f9010fad06"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9b68b161921e4dd101534c347be8dbf348646547b53ce1a40f94cddf30495066"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2e944c10c2706518adb037e14ab2777fa5b8bd2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2865f7adb6359411ab236692166241331fa515089660e29ecf60a2e381a2c7ad"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f2c9d4d892aab4e480fe1f8d5db1f741e35ed26"
os = "macos"

    [[PROJ.download]]
    sha256 = "ce9b3217db736ce0f01f26fd9851c53c312d13023cd886090d974bb3d2e1256c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "282c632a8bbe6b66c214e9a69d15cfa9689cc00c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1e96da2d3c6df7d0a630c0a3c02cc65f634c3f2f946eef65282b1ef5e0a9bf1c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80ef7581a191332ace3fff0c25cc7275cd72a139"
os = "windows"

    [[PROJ.download]]
    sha256 = "7da50cb9a6cc183145288dea79519a2cae9435ec557f37bfeca43307db1c68cc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2bb94c31c0f73ab9876ea44d132ca6f1f99183b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c6752450194f9379cc28c7046bb45200aa5acba8ca7d01843169aa2e191af6a0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f45d971f026c1385ce72d3324cc3c0d38a813636"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "4fb5d82bc861581f1a0b28cf00d37ffe7a5220097bd6c2068a6726583fada806"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0468432898a3c3baa44dade4f739f06722b9169"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "85c0c0054a86ec621a7a653a593d81d05390e8697caa0c53d6c97c4fcedd33ec"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1542fbfcbd4c5ffae606525cfa80cd277122382f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3f272f70e8944a1dd743200e122085b3dd606b391bb43ad29f37e669c6adb4ea"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee07fcf064b89a5bd9d4918ac0bceb22b17c340f"
os = "macos"

    [[PROJ.download]]
    sha256 = "f67347b4ddb101495de5066f48cbec86050dbfa9bd75e985f66b05994520abb7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df2b2799e68730e0b6ff922c0f7640fce5373d3e"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "13de129d6a4e5fe921d53d6aa9524c173a848a02b2b21023706776c01767ae86"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a34a284ab6f1be1e128bf7ada6e36c2830954644"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "cf1100622080507fffcc091c1c3d4ee8b6194a8e34a64c9635f363f66a54808f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0d6d8387ebe754d45654d92abfc45a6cd88af9c"
os = "windows"

    [[PROJ.download]]
    sha256 = "7a745d67640bf5dfd8c0e0fd5000306f538b9939e71253425cc61857834a2968"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf722d54b3857871fde162392f97a773b5735806"
os = "windows"

    [[PROJ.download]]
    sha256 = "aae5706a5292804c1aa130e7bdc2ab2ecb82da3b7f90c50ad31aac119a7a7d0a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a63ae7fb8e7d42caaf4eff27a6321d54baa8e9a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4625d417cbb890be16adf0b8229d6ff3d0cebd77c4d0262a9b790db8e19a14cf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2dedfaef7406396748ab7602cc9fc484fdf7f3b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "75dc1e809b2cc3e5aea65e6d6aa254b97337a6120465cbd6330bcb87b4132aba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f53dafe6ee37d833340531e47555d003812084b5"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6960d4a2f53bc27e1d71d5ed71c2e26018120778cec4933afdf03db14224af85"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fdab1ceab250fe1aa8d6a1e75f1e25a086881f1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7487d56f11d5645c661ccd3b7412b24a704a10207c3cb48486cf04f6840c9b02"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7ce576ed11ec87b142e823c1e3e4c02b75cd2f0"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "24b4ea2809d46f10c4f8423842f600e7097526a8de48077508c3b4985344f1fa"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "424acb7db01149ca1082f64add9df7379f0f8cda"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "68297bc4d378c42851c2625a313f8b2fcef4371952ae23a4dcd807a3cb7460cf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+0/PROJ.v6.3.2.i686-linux-musl-cxx03.tar.gz"
