[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "4f4857c962cdfa808137569ef23e38a50a1c07b3"
os = "macos"

    [[PROJ.download]]
    sha256 = "ab04e3817768870a307ea804fa2e898a0595ac16051476f3b870d111e5e7bf84"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01422511abb14a0caa0514128a5896f752d0cbc6"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b574cd03c3843b59d6480d02d8a4e4f11c8b547aeef761ff95df245121a08470"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22a49ac5e420236f2c1f035d532de741dbbe24b4"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "84cc815821d1c2a594abb746619a317293ebe13dc62dd81a957f5b491bc08328"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "04063ff44d8fa59a60065e521c706f51eb265c1b"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "4a4926e8208dd134b38fddf52a517be19410c25c57d71c4f97c7ac08c80074b9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.aarch64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e93f627cd77b314ff49ed8f2b0c440502381f9b7"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9ffcfa6c0444b8b36535a173627e50724e6b5be65154a95d6885fe511c9906b2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a5309998e6ad149137e3fca07dfdea5903573f7"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f96aad004f77e039ca64880083d8ba73f85901eaa14ee4f79fb4e08065a4cd2d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55c1a4aaafb9f291ab492bb72b064b810072a7e0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "abd441665b4573294e35f3582908f8bc734101adcff05f563b60b68405ff9f98"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4c031dea340716a092e9152b34d6d9b63bfd147"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "c7de574a5bd8b62580353f77eb745991c9b54aa8c95d1438e3f496989df443b7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9985235b39fb7ba75adf59d6932b36b327a8107"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2520a254428e49bd8a5a69537edbc0042ac20b37a4b56a141dbdb858b2b4d40c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1da9fc8ab47d13f4f6dec9653e002ec05e242e1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "60401b86758724419c18f2620d4c22262c84bff6f4e2e6cfe22c8f4f2c032bab"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14ec32911d0e50e03df405de18fb9dc0c26b913e"
os = "windows"

    [[PROJ.download]]
    sha256 = "67180604dd9cde37e2c5dd09e54a7f32cde43337d404debd9d547212d433d546"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e53b0a5b85e832bdce40dfad3c1cf6c595b975"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "63738cdac6f3fbec7e0052e2846a65c20bfa8c50c7b80bc8609a1749eaddeb6f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a167b963bc7f86d98ab01af1776bf01275191ea4"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "648e9106883cd6a8366a74f825cc4f3956eb5e34b0d9c4007436b73408246c73"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.riscv64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "7b2829b13f5b1346b2c0bf60d9d066f514a83b1c"
os = "macos"

    [[PROJ.download]]
    sha256 = "fb61fec22fbd9dfd4cfafe3687ec2b70e2d2647fbb25def444b86f1d0409c708"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56734ccfdc898dd0eac01cdc93aeb451bd655e92"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "3ae7bdad47780542f6583307f9061b258a67e425b0cfa5ecd8b7c7b1cadf826a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "483e44d4d585bc1e9b1479a8b1440675bb84f6f4"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cf6a9b32a1d5cd5c69abb36db4e16403a61de564ab0c924c31fff72f26f3f734"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "df2a3d54a3b28cb760601dcc176a7b5842ae1dbf"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "ced6b44da6a1542a46897aaaf0e2d90907bbed2f990d62ed368c1262128a49c9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c80bed0b6b0dd4e3a502f5225d91b2823cbf7fe0"
os = "windows"

    [[PROJ.download]]
    sha256 = "f9aaf03b9cd20b3562387878b60a25b9701e5a9312d098c4b357a41a92f9cc47"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.900.0+0/PROJ.v902.900.0.x86_64-w64-mingw32-cxx11.tar.gz"
