[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "591561a11856ab32eefdd2d850a00e7ab65f2856"
os = "macos"

    [[PROJ.download]]
    sha256 = "ec24ace7b91be7683cf6c43b838f4e4a3e9b1042b5cd20d28b0920f356c3b4b8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9487c4e17c5b9c608eee5819f4f7a021cd79b1fa"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "03ee888fb554df17b6abddf57ad7aa1b93b336ef5c090aa32171642654c20944"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5f0f2cd68c619b86035919f97630bef400ac2c5"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5f30317baff01f4b6ae0e369ee58f362e834fddc89e6b54e107095f2ade4409d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9ed8e217ed97cac2a105b690510d638a28f1ff9"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "02b560415126cbd49aa856b506276f72486274c817264dea1f2e8027b2431720"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6893959e1cb6cc37268ac5133a0daeeeb3209a86"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "bb0d7b26d80d277d0d426b9688b99785a16c24c231dce516373235f50ef23b4e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "312309e34ccfad6dbc0a582a06407b7ee623fd70"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "e9d651633ca57cab1aa9b00690f25fdec37bb3dc859da65ef1732b3fada34920"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.aarch64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b01155e4edb5659f4a83f8b1bf8b668c0ebfab44"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e53bf156341b73f57d975e7f03943c398b771bd6bcdb4d290fcc9e653bf702eb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab75b458a206255dd3e4c5ad8877465e8d5af413"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "62826110965e1f6f9361434c4349d45eb9a43cead24c4f57017dc5c27675cd20"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08c3d5050dd20751883b0c06f60bca3b31b6e055"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "676f434996e9f91ca49cb902baf6dacd7a4a18afb3efcd280b3e4425a19772c6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2410c2dbed75b7ad7c93bafc4c1e3255f3e550ed"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "48d96454dff9436ab98e848361c6b325baec9ec5768bedded16c8acc4595e500"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7849c4e2de3d71d6ce5308cddd774a244b6774d9"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a2f9606534d1d6eabc08e33ea90f78667608da327ee9b3224d37b8cf7f02aa57"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6eab4e4117bbd99b834647b5f57f9307022f64c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "56e69cb99162461052bad873d521e3b577d00bedb3feef46bb5e9273a836abeb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e844798ce2bee2a3d536255a1c761758360f4804"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "6d69db0e57cd56f26b497baa81886f66c6e2e5b0df5210b323a358c37f6ccbcd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fb46f529339bfeb5648a72a904d2b4759d4cc2d"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "01730675f63ae28abf9f46612d4d8c58e21ecca4c65560fa7cbf39b1ae97ef07"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cadbd81c9064d870b59da775fed8517b373e24eb"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9001797f9c16519b8b596a812f9be5461df9a6f25a96831e9ada3eb55354b1f2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d0059ab198b22a3ed51541671c40258be799733"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "845215f56a26c91d8b141c938eadfd27ae5bb7fc8075a02606c0d556253c97d6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb539aa66afd4a3b7377b0be943b4b7275ef8608"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "84338d34a928ee5b72c8af3751313e5b715b7537252adab7bb586f99e101e797"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deee817bd24cfdbbe1c673c2113f361bf81225db"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "9bbeead06bbe37e6f86c74183c10f72ee4eeec2eccf512a764e3b7314a76cfe8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86acaa90a87216e5628d7b6bbc281101a591e1bc"
os = "windows"

    [[PROJ.download]]
    sha256 = "5bf3b708558c3f815e9ec9627f02dbff2f13e8f499e9a5e5ba04a1c607260cf0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bc34f9726c176d234cedf0e74aa86d9e68cd68e"
os = "windows"

    [[PROJ.download]]
    sha256 = "46dfe174fb86821d69db19bdcf3997b2d706806bb00c967a2ecccfc082aeeb68"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40e86d3cf9e046a9a299ef200cec0a2d3905da50"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1a0e73f9b50d1c4c79cec6b1477e25e53931c8a48217a7fc7a318798e0e23356"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71bbd153f8d13988dbca3e7e45e5857674198930"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6dbf27bbe7929d47cfe398d01a1064d055734e3186174c6fc7eada7ce544a197"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29d0ec9502bdfccd7a399de3ddc5f9b61a8b4785"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "80760bb07268d2a3b527e48521eb65c0646d257070892703c197b4bf4a76b26a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.riscv64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb96eaca967079fbe9ad37935bb660e839839042"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "aa80e5c4599be70c0c9b02b2a42d02353084080263c09e37e40eb749941a2aad"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.riscv64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "aa918c89f65465701e56b5b74ca178e4fd9792e1"
os = "macos"

    [[PROJ.download]]
    sha256 = "e34e8c5789f628b7a7237e3183182a47427c4fe9dfc10ceea2843f6c9f344a99"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23aac95652145ce6ae3331af9fe49c34da8f329a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b48c84b495edb246a237f6487f671767e3c4b18e0067f833d0b743bdc060623e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e25413977e1aa52abfecdd2bee850e964b8d477"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "03076b7428bd2e6b94476afb9acbd39b616a5aed59e5eb659183dbf704dc12c5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee37eda2253bb1b7e93051964a6a5275679aa3c9"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4065d89932544b3e79517a2b85723cadf02840272f01daa58bc4be8433f4aa11"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98be31a6625c211bede9d2fad0c0c68576f5e5e8"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "53eeb67f9040897d98da6210b562b2ed3b2c3379cab5e330040c005c95fb000a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "7f3df3aec47cd8bb10d9f994416293bba8bce5b4"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "5823fed115cbb903526410e158322a5db00bf9ca5edf4aa9976b8308fbf31920"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3853b9bf25db8955203d6aa2961236b73bab708c"
os = "windows"

    [[PROJ.download]]
    sha256 = "b9c18f4b730b7b01fa636e6b88f56408ef9abdf1394e907d62d01f4c745f1eb3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b979b6ee150c60404cd190d8c7f8892bb97d27e"
os = "windows"

    [[PROJ.download]]
    sha256 = "a077d1cf0936694c86c8231575f5e1264550335d03dd6342df6df5f28f44fd7d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.0+0/PROJ.v902.700.0.x86_64-w64-mingw32-cxx11.tar.gz"
