[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "dfa09fc5bd33a68e75b575d8d6565a89814949c2"
os = "macos"

    [[PROJ.download]]
    sha256 = "7e8da3e5e34d5ca313ff7e9d0db51114579c895e9063fa87c44fd6267cbdfad9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38b14e2b9caaea46dddd0125fb4b9fb7e31f93d0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "72101edbacbb6d3b07ece2e6acf439cbe72b0d173d92ac2efc3cdc17d2455c2d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ed039f1f14a1b4379af639cf9e0116652f13137"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "3fb614d9c6c8fa35583773c76d9d7afa0b63376a87d5b129034188ae1625279a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d52b31a5ab0f8bdfd45072a10823a675b1813096"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4dbda3d830b04072524304fcfc2a71efcccac0dfbe64642a6ecdf052f4402b8a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b91df11b981f3e624abf172d3d7f4dfddded3f76"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f5c4124f038b13bb58a942006130c4cf041de7821cd5f82ec0bbd7d936010bda"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90ceb07b55cf287c07e1f41f6b25c3318a81c889"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f8850d9b3a68cf9380876a106a2e834230e22115a184021db04fb49dc186e9b2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cbd375473eb0722095849713f8bf025d003e60f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1e4fcb6566d13b31c4dad9f5f99a3d1e4d535b7c9840e2123ffe1c164a226f7a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0995b3dbf0e4726cf9416ff3994ff066415c0828"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1fa55d42a75f6ef1177fa63d55f2720fb916789832c32fd6e3964cc270be8db6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35cfeda99cfd130c26be4ab384ae88e39fc574f7"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "5ee947d25b366979d4628a16c428f58ab201d3518c56ab541a348ef219287d25"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdbf28b3da6ad1440a72482f96ae9702a6b850c0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7853f7a2bdee913f1faac474a1fc7e019926181e926f736858ec93349bab6ecc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69261f7ad260380a6f25281db98e5ce3221ae2c1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a2fdcad8062739991e14e586b6cc9b115257d75a682b87656fd641c745a31c6e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd15f2c6626f1f4f709ff26dfe389b3ffdfc344"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4368e722c1bf6a881be423a46b99e8f8ec50b3141e2eaf44c4445c7bb3f41417"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d30165f7e161cfe2bbc0ae5cd02a309b824be26"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b6d53682e21863fbf18148bf886938bf1ddb7b0b0f6c91bddeacddfbf24b9ad7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02fdfa9c4ec65cb82f72501ee84875e85f25e182"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "be4a9190bbe647034767ec59aeb0bc7ae215bbd1ecbf9f77c8b27f96736ffe0e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8182a855cebfc99447158c148069b954a10005eb"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "eb9ea9db4e800de135e4d7956285d557e8c24ab2656b713d8d0b81f203c4e552"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6a7eb7b9408589e479c6b514603347d702fbbaf"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "d04f63489067b19549b36c78cfdebabeca53ad30899e47b8fe483070c09761a6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d778769f33d45685c654adca817f719f7c297660"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "60fdb0f5ea268d356ae7d452e28afd47f466692fb40cfd340dd5fb444eee4aa6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76582549f999c63b65815bb0f8051a7171f1c419"
os = "windows"

    [[PROJ.download]]
    sha256 = "979dd1c73d4066059f8efcce45be80ad68e73a349fd552515468354f2df0a704"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9e6818040a72dfde315da4202aeb802fd322939"
os = "windows"

    [[PROJ.download]]
    sha256 = "0348359bf4faa17dfca9e4687e0150d7579fb9281220991db795d82a328b3f25"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd785130184c59362aa750c2a202eff5da11e78f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "cbb1c90ce7fff9d040fb63f881f9a0640d326615f4dfe0770b57bce67dd18e85"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fce89b962467b4e2dd1c75611080c525881efd7"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "18c024edf4fb0a714ca78a3fb6bb7c1aa81223b5b6b8ed2bbefc82606695c9e2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "b9adff9483d823a0abc9db1078f568cbb3ee4711"
os = "macos"

    [[PROJ.download]]
    sha256 = "647a25091f7fcf5d273c88c81e87ed2078570f872dc28877119a5f38e29befb2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2d7e9a57ad40b6574237b23729c8234f658fd3f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0c6709a84ae85384add620e074905f38205c44e0ddaa29fb139475ba0fbf0bec"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a643038d2adde781829b4467a32afa307e23b51"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "619c930af3a3f02841d7c3bac7708462dacc58e7e90d86b32398daee85e841ad"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49b44b009886c3f83945d5aaaa55bb6d1c624aad"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8f7a23042f0c8da852a301d955ff872629ca0c7257c62893bde6daac34accc85"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3327f15f9c6b10781d85879156b5c070aa01cbf7"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8701a26c6557395956b9200ab2e8ce07023bcfb242b17c2ef095a49cc2d5b2b2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "16734c5c7c7583c1b5d45d2ee88649dab52f322d"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "49d606658ebb229b06bb94378bd44c14f0e80b9322fc49e7251032c68db845b3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a2cfb894c85d9858400ca70a69b9d58e0130a00"
os = "windows"

    [[PROJ.download]]
    sha256 = "4724c58b926f48bac1e65e568a2ca51e908f8a334b5da613512c656e70c1754d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2d9050c5dba019ebf272fe7da44f78c5491672d"
os = "windows"

    [[PROJ.download]]
    sha256 = "6ab1f26d365b477abf9f2ed9db16b41cf7f87bf47fdaba493eb1c43ef8686a76"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.100.0+0/PROJ.v900.100.0.x86_64-w64-mingw32-cxx11.tar.gz"
