[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "a799f4ba8b350a440ab68a5c5c0358b5637930e8"
os = "macos"

    [[PROJ.download]]
    sha256 = "0cf48efd42f75ce38f64e0c582582a64b7c03d86a3875984b7a3a5ee540132d1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37efd48b9e5abe53645513e0169d452d897c26c9"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5b72bd143f8114a146e2393324da6255a4650ee198d098b514f93defb8e14f1e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11742af1ee05079a488b572d1061d1f438d3a56a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1b8463941b26b34bc867933695bbb0a0fec11f217d9b00c8251573c8d8099237"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c561d5a76d2c7754fc77d7d104ca385d11a71fa6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "747857bc7123fecbee1e74f662d402ceca63394a7b4cd46c97b435575d967520"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de15d51562270b64314441579d691fc9dc5abe01"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "70b18d887a2d0343c720d19c88b6115d95110a6ebe61552151bb9bcb544909e8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "9e4e7de3a2625b11c3407af9a7d07f1d710f3d3d"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "9694fb5bfc2756a9b71fdb76318aef77a71c8668b06410c9f6321013f8300290"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.aarch64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30bdfcac20b4880e3504786f3349f02b58c85f70"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e31743cf63d17b330b2cf7dc52300fb8a91332877ad4ab9d71ca00b7c891e693"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34c7e6ba3e3580b50ecf32e38e1a47463540fe34"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f659d8287f68396866e75890bd2c74445f12657a5a75e0f3f965ea7b94b7c203"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee8ae7db6ebc827b8d4f5d290d5b02f7d1bb00d1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "36d0054555ad09598e010efe7cf760e070f0ae8b9a65739fcfe3bb0b5b635b58"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb418f7b5513169abd51d990a0e64e3f0116a55b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0859ef366baafae8856688581b3ed1373e0fa5b005083cdb81a0b763e6273c8f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83aea452a7856808cab4da2129ec59bf71392377"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "76217f676585cd26aeeea877045bf66765d4acf4c9301561cc3ea0aee308a64f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9344fc9a6d45ef0015025adc02d9109af6972304"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "327ccfcbcadbd6de2c773e9a39904dcf5331f8abadd0fbec099055bd9893344a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97e611b5cee655ecc33964c2dee73931eb907e1b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cc3edf3dca1f2122c87285bc52bfcca4f3d82907f9dfae0f755f854263d6c99b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "767d006fb4bf7819be52f0754f54f727958edfa2"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e8d90d799d81ed007f9cc043c07987e0d30a65683991f2700ae262417065e4bd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b20d5a1c7225450a128a62b93bd03423f57836c2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "146a97168c44ec85d24772a7d75511cbcd8ad0e126db264397bc43b596903169"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97e0533567152ab9256f0dc7ad5595bb4e818fea"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "12c1c75e108a77f14f82ecea4dfef766173ff73e2129c8ae952b45008c41946c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55a5d7a1c4b7bc9e700b681d3dd0b6360394a7fb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3f89a4c7371abd571aeabe6227ce70902f261d96f7c19cfc698eaf639f21d867"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0be6b8ef06c0955b23792f6455a332eae4e1a74"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b88f1ec28db2bf8c290068743a471675a263d8f22788adfd8c742073897a4a2b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6728bd7f2c928adbba3385f39a72834ce9486cd7"
os = "windows"

    [[PROJ.download]]
    sha256 = "196457b272a198ef6dd337ea0850e4aa62d753d7d75a553952cca8fa4b3b383a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66bf604ec598fb003b768ee8b9bd3288b1b6c17c"
os = "windows"

    [[PROJ.download]]
    sha256 = "34c8ddaae5d1643dc83f79c2f55bb235b5409fae5f18c20aad6c63337d73cafc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77a77828f1111b4aabc7db0ba05b1ea8322f458"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "ec51b63eccafadbb5971241583a72bce42ec20ebd465051afebeee803ef454d7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "978e20f5d39fca6b815a7aeaf192e560e8badb7a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "274b5e303e2c091d2eb7237642aefbde1cde3403aed53fea844af3a1490426e7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6addcee015075fb76131509b9490b636b4ae094"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0ad408035f3631779b3ad20ca54096e8c0005dcb499c4b6fafe2479c05c64a34"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.riscv64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e847ca42972be5b3ffc9b99620a605f68d2dce47"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1df12344280075cd50556c27c43fc72dd686ae22aad5f846efe82cd2bf61fd63"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.riscv64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "2b18733cb76c4c27cc995fcff9a149b06f564f06"
os = "macos"

    [[PROJ.download]]
    sha256 = "3cd30cece1b3dc5cdb982ff20d1c3143475c7e7b75d6eee552b72afc07ca31e5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f71890936d480894e622ae09dc95eb420aecc3e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "788e248a2f64d691f01dac0262f26b1170fcc9fdd0c48b8eff43cc7cf0bad2fc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dd7b666aad3e87376603c7617e3cc0263d72c88"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "884e8ceddf055e41a61327871ff86ee9f5879995fee51c18e28c1d87c3206467"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de8c827eb24a49dd7bc2f5f70e38f94f4e5cb66f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "38abe6523b9fab4010c92cdc1f4265d24e6c108001df36ef06869a354cd6ef56"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d4959da025418a0adaa9a0dcf5dfe91a9c42e32"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "5fdd462d251f62cc9ef0b215f4ade8e966b0bb66b2dc90d0d50ad3f0c61c53ee"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "cc56e2abb26d44d1c817eb3298985d5af28f9b09"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "ec5b29ad1aa2d0df8555ca6b5c756992c1c69634c42f65c11ac1d0d288dd51e5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "694b8b58de38505af2eb4a414ef5c06861bd8b3b"
os = "windows"

    [[PROJ.download]]
    sha256 = "44d4c4c580ba3f66055249886fa1a02afcdd262d9fc6278142bc80c7ee765d5f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb61d24895a5cdb6a03e51121c4d1c439b77fef4"
os = "windows"

    [[PROJ.download]]
    sha256 = "400a40af4655a59f59da140bf81a7871ca7550c55c3341ecca2827ac9fa8177a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.500.100+1/PROJ.v902.500.100.x86_64-w64-mingw32-cxx11.tar.gz"
