[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "53a1f1913ffb77ca87b5aaa9af754b865706047f"
os = "macos"

    [[PROJ.download]]
    sha256 = "aed5b0ac7b298106870f897f63b6670f5e7fe76cb9fad02d148b979dd6d9a288"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a508386402f598c5738dd3d962e4846b93e26952"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a7c02aa3ab90d9a57d7d41ed1e8d2781edd85383da66054e161047e57aa7df2d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc5e58b00b640ca875477f2b218a6b30c566d6d1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c8c9b100df33a221320d0784abefc9604c518416178a57c138b00a695f401926"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "995ca1147cbb30fc16d6f1405585201422c986aa"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1dcb7776d6dd73797ae8698ab49cc4ff2ec37141f03e1a1b5576f37b78135281"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d200c4646f169d65a884e9f8adf3b02c0d70ca3"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "7f142005366d3dbf7394fa33cdbe1886c01fd79c920defac07382ef409b67618"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db2314eb0bcb41062170a007feffa0795475db9c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d8d3f3866dea391fd6d58f49d1ccdd4c7c33edadc64f91bc1b0a9d0cc7835013"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79cc5b6d1ad091275b8d5e19f30a9a5680008739"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "fe2ed20e7b0ff3b9bcf50717fd0bb63ee962e0a3a9f6d180c133ad55d7fcf1b1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "febae14695fc6a93073d57ef53adb4623ae6ee96"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e661bfbac88ae5e95ad3e7c02e968d88d0904501ae58c47d8615e6e4e9a382af"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d3db5bb3eb7d958e93bded682fc9a630f33520"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b6c96ff43915d507576ab2f960ce8a071a9ffddae6e6e2b0d9da15d5b6f32909"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9ef190f11cf97c81594211b1ccb6029c5a150d5"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "27b7e500ffe810b6c6a7abbb51d8aa4332741c81c765c98c4cf20dd4805a83ca"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7145a27d282218d496a4d48eb2b0a68c275b0500"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "899bae80110d72c76fa10ddf84947e3cdd7c2005046708583bf667ea985db5b0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b07dee90972541923cbcfe1b24267399ade7563"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b8b5eafbab3e9295a8d08192659eb2f2c8e85354b4e0cd06b864b04cd4ea2b60"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e202bed4f3ec9f9c7c48a4689eed3454fd6aad2d"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cfac1bc440e0bc2f79884fe4d5593155d9811b5e7abf9f48881c0473bf4de451"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3f6a195268026681e66655098c3c44974323f62"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d6e98830af280b82d4df1d0211a69cb693747c1a1ce05eb6e7b4fd62fa79bc73"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef8b81a5b0d7d8bc77ac129fe7e2343a3f94e7ba"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "057e0b344c58fb986533c88ec48a8ba736fde42b3b34487c0d5a8601186f89c6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5d52a25613eb57053ac3840aa29a3c2fed5dbf9"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "7c1934f30bf9a2d28e94f1f03c9e2a3845675df84ba18899601f7d4ecd63b481"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eb818e4ecbfc6089a2fdf462a9eb15a89e6fcce"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "9faa8aa4e2b5ad384f96ca60299e95adc290f0c470956771d3fc38a2cdcb8bdd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a30d375335d9a1a202f94575ac562f226c8660c"
os = "windows"

    [[PROJ.download]]
    sha256 = "e13df915113778138792d2987c2d77139cb3baaf31218bc884f6eeb4b33670ef"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d8566400a212bbe4e55f297bc9305e278b74d4c"
os = "windows"

    [[PROJ.download]]
    sha256 = "015ea17d496c3ef493c1cfe69f275fb040ca8873f88c8ff4fa75b5811e0c65c7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b7b06c33c6a44d8ff65fa472246aa6764502a5b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6bafb0bc4382e4eb27f8b581aa61071f0c9483ee6c0294c5430de475d91d2c61"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a54fb78832436c369200a646c4d8fb4e813e6e1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0fd6bb9bcaf6d3e70912205432fcd047ce203a88a53fa8ac14e351ad72d18d10"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "98ae92ede4a86de64a09913f1330a1c6c0414359"
os = "macos"

    [[PROJ.download]]
    sha256 = "21e57e88efb429477bbdfce293ed196c20c4f887aaa6c577016209d0901c54d9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b024bb0f0f5d35dd2d6ea42db1369c372c86134"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b3453f8d594c0be685f65d2b8dad542d02e8727c54d2bdee8507262ac7f17295"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5db14e3a5db1fa30bc1a41558156fa2a2a72cd20"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "78114e43be42b0da5140715cf592e6af5b827250a65e8daae59ca4ccc5e59768"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6655dfdc0f488fe07927fa030217896c44b319fa"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e30bc29156ff728496d79402c7d5217a69ccbdaa64e60990a5cfae6a0cae5bf3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b35183b07eeb1e70c0465b8154834bde265e38bb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8fd8faaacaafc374120f173731146ebbcbd08bbfdcc211a4691f35f60c1c80ea"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "81aa739d5b20984453af8df1b71580ad96546622"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "d44c8597faa2d42cf7c151f3ac067355552408c3d7fe34cae8030f0cc9586b93"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd369df91caeb12e334b0762248e8753f87dd74"
os = "windows"

    [[PROJ.download]]
    sha256 = "dbf6583c22154b12cac53c9f754b5b48887df1a6886c440a0720b804ab3050aa"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a92056bb5245200776914024d9a9ec6e44ccd4e"
os = "windows"

    [[PROJ.download]]
    sha256 = "dbffe477aeb1e2262b630795d6c03302f63ea632c443e4ad81c7b6602748b9ca"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+1/PROJ.v901.300.0.x86_64-w64-mingw32-cxx11.tar.gz"
