[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "b821496a52198068e513c9605e2cfc5af579f4ff"
os = "macos"

    [[PROJ.download]]
    sha256 = "8b78c974bd285af61a3faf2f63fb3fe3fdbbee2cde549fac42a97835dc4483a3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "803546bd220b7ea1f351f59ddaabf92f2e0d4478"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "fe17300f8841a77e967922599f8bafcb0c0f2aea27e169a390e74b94478104e2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32ac2367fa6abf998d97d4fcc66958025a81df52"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "3aaef5decbdb55984a47fe4c9989bb5cbfa007c500ec64588b7e661331894281"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b989526ba5b3132c1ca403f9369f2d1ed666a94a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "378a7f8f190926883428a270563d30af98ea90be35077f343e71594c2a513687"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c838ade85f6e1beb44018d2b542998c6617670ea"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "73df447b3ea75cfc124622dc343c84716d53f52a5a1ba4944de09bfda2c01210"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "566fd91c5d41faca74315e17d008d277d84a2736"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "461edcbfaa8c8e1ceb3299c045038858fc513949dd255ae4d475212f19fd1242"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf3fec13037b3cc8febc167c9074a9e7b06b5eaf"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "01e901f2b578c22b93d636b9d5c411166b8c7da2cef1acd09c3db0bef70cc9be"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "957ca1b9367579fa7ca212f8a839dbb7220adc8a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "66d3f544e0634e559216329deaa8b34ae7abe44d2e7d59b3656db476e0dfa4a2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3080cb3484267d5d110d6a74feac4b4eb383e63"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e7157313e960e3e30cd247e2c72eef757f91514a97d255b8fa41fbcb10546906"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "081d30e751ef520992ebbd4dd1d05cdc1a52c355"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "41bd25b209a96ac368917b2c34c51381f5740f2ba942a8020dec5ff79f5f7991"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39b710f157c4f63dc4d4747058bd171e92c5725d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f9b06f599df9cabcb91108bedc4202b94ebe08a99e36916f1748fb0cbd3a4402"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24d72d94544389d90dea84e0f54a0af25e81ff0d"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "dae37c5107fcc4c4b44fb9d54a388570b37b677ccdcc2219c0888fe7ac47478e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c11f1e3fc98b384c0473e1e26c0bde03fe6444d4"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b9c1297c17fc9a2c3b11a213bd5800519e7137dd952169259e22c1059b0f54b6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "473acec856cdff07cdaa8a1f0b5f41b0eefccaf2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d2b17fb87fbaa531f58fde602ee880e2a472e5901bf4a874a9d72a0c81485d9b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d60fa495d13f557b0333346d97af4687f7c3b465"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7521717bd26b1ecbdee5e854cc826598a50d1b6684a4975b8af952d668627c8a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61694db0c3828f122b3600d057e05c5b42edc481"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "523297dfa4c89e315380d38ec33b2624f9468b353752f7a523a173c17d0fbbe4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef993ec5fe5d1e55696366517819fccfe7688efd"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "18420b0b6fdd581881e6e75dd03fc49ee563a90925c4f4542ecd6019b9bb3ce4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a718308b10677bfbbcabd95f90d6d69d6fdeb29"
os = "windows"

    [[PROJ.download]]
    sha256 = "39869299778acfeee63f163a38a6423010a943b41d67b5ad1d5d64fedff9b1d8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e89c5fb5abfd054cc2d48d5890db97047a87f9ed"
os = "windows"

    [[PROJ.download]]
    sha256 = "8bcce34c0f72dedd923ac5cf1583926112a0a13d2e416c5635b5bb7514e486a2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3221f6a43377aac81c6f74195d1432444384ad2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1751ae4c306607fdae915c3cb38926fe6e62ad38f0d96fc26c2ed10406cc60a3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8b7506d42828188199b6609dd0e3364c6c0852f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "3972824fdf83f4d648668ddc27e9c2f7b282e4d5112bcfc7c1c6b5cd93fea83d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "525a7050baaa2b0732225f4528525dfb3cfed1df"
os = "macos"

    [[PROJ.download]]
    sha256 = "e6e88a86d6de52bc8ba3d1a56dcd11d955f9657469996642cd0a447aa90b2595"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e43cb5d62eac9dbf709076b0cc07f5bc7689fe11"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "87cffd92d61b16785e009a36b3e8348233d01f478936b29f8490b24ed223cf08"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7157abe758db850e6898dc19263e514438f798fa"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5c76d9f85253012831fe44c69225f8e2f9b1fd6f357d95385780c48500861c31"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6434279cf0c5d165cd0f3230e8117d286fdd6c0a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cb5315d69ed98abc1db2e833da7f5a75218ce8e53aeaf2c8dce585378ad1794f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e220dd6e4b223f3340d793e8e7269acd349d0630"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0fc93e80ed594870a243a1d272ec81595804fab2f8e73c93e2fc5e603442a840"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "bacfe18e0444f49d3439730d228b7f411a680d17"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "509e54b71bf1d98f7d3b6af099e82c0447a3bd70220622409ac6d8d6881cbce0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8152354ec2fc4c7cd33e8232624a1d35d8015278"
os = "windows"

    [[PROJ.download]]
    sha256 = "042a2b021f72df13a74c488adf2e7d995d8ac686b32aecd39979c4975d221ecb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebc0e97192332054f4ac32f5921df76d0ec2db06"
os = "windows"

    [[PROJ.download]]
    sha256 = "4f5c8b9c453e2e6d9ee38b749d0b7c748c3385dbaa0fd766b1e7b3124a4300a6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+0/PROJ.v900.0.100.x86_64-w64-mingw32-cxx11.tar.gz"
