[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "3613c29b18185ace071c0fc6595f402f78a1b5e2"
os = "macos"

    [[PROJ.download]]
    sha256 = "d65de1f1b6dee03ac81d4e072a0785d9af286c03d06c16c2d087ddf6f7146664"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d2e233ed223187b07d745605252e793d55bf65d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "1876586ac6a6019187d550eccf4db3d68efb319495d71020b1073949db2e8f51"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "421d862e081b36673afc5d9171fbc4abee68ba44"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9993f67999d6e8961f50e21e0b270175d5cde7793a94aa53d44aff5bbc243eaa"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76acd60abd22a528e467adcf048d41f3f4b2f62f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "367eb5ad5de3b793c2352149ff5ebea2e86469e85376fee7ec4d9fd2e4c07f9f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb9a2593cf9d1202c94e56c288d3952cdf5d4086"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b29ea2e165800eb1ad2a4a160374c1f48b3af86e86d87cec9278a60e58341305"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0375cfd01fe89301f2434d212289942952a86db"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e98275fa31e1b294cb81517d36d939b8664f2f73d8ce192586e921381ab6c75e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02d410b5f367a417d040b6b1967aa5f6275de723"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "57ef247a11cbf8cd72424266cb85b0548eb9e76baa492967270f01272b9ad259"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3638e9c273dca231fac5376cb73a514cc683f4a6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "ee9eef5dc0eba789cf493303d5c3bc8b98bed2136ea0b4106036dfceda889baf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a55314007d2e29389ca75c1dbcc5a0046d20c65c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a1eb98ab98987ab8d9de71375c501c82577fb8cc1a0a94a8b357bace27f7456a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33b1e05dbc20667c1e1a3459166b2e34f80dae2f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "585a8bebd4ab7a1557044e90ba40efe5cf192d9fce3d5814a391f9827e9f6660"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ac37f1cec4f381a7912abe15d68a99c69116dfc"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "ed96314942aba32c705de200122c5f5042e795ffc648c3423ed80082d937014e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8fcbb10885fb1b6dfd2fdcd3394e8e544df957b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "2ce619f78ee92eb523c60fb1ae53666ad543c196effb5fe5dde833d9bcb4db1d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91392d842cc362a6f764ecb55803123b8440a5d3"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "7cf62984dffa9be92eb6240d739b5d6fb3becb3c7a610fd76d022512473564a5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235a77c7731e199a66240d0f0e08e9c9f2b12806"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "10bdc5922d4a606cc7efbec4358f951dce026928d5dee5c2eb4e6e57ad5fbedf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "492d3df23adc8bac87a75a4bb4a67dcd99d0c742"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "06c8a6419557fb8767d31fca220eed53ee56910bb80cf09063cb4907cb1787b8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b73eafa1e9d906b8bc4deb9408659c179a924aad"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "49e205a9afc6f5a9b3292a25b2704b72a18d3bafa3a0a4b1f90e6fbc4865fd99"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75c172b30282f34aab7f20f5834ae3e28703c183"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0a41fb4e8507bbe36c59cec33174db65c0acd32acc5e051f6d48d0748f3fe129"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2678b63b6158757746bdd26672ab2c13eb7a8aa"
os = "windows"

    [[PROJ.download]]
    sha256 = "bc01e0a5c43beb6c61c89dc53571f1a8266e101856174184ae37d00096d660e7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b84e4fcead9d0d7aceb94ee024cce3846e41f765"
os = "windows"

    [[PROJ.download]]
    sha256 = "7bee471dca1971358a4139c5789f11867aec78679d6d2ec8b18f08172aebb354"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c4830c51d9ea91367961f593320442e8f6ead1e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f77155bc35ae0be31b847e127a9fb9ea23a051c936b9e0cf1e2bd9241853fc90"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd53b10995269f54f202310363fad8b91842d8f2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "744ca0afc0451498afd98c61dea348d3fe457bf493ab63fd403339097b7f4e08"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "c2e95556934122a60b3aa482046090a8fe35aa9a"
os = "macos"

    [[PROJ.download]]
    sha256 = "4cc96fb57e6b9c3f9dfe18dd0987d62e4b4790beeec1f5fb5fa0f93cf45988f9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4b966b818f966a7d0b0c05e17b7c74502acc1f1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "fb4d2098aaa39a49c911ff3e9db782b8a9f0b1a7fdc61bfb03687af17bcccb84"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "112e2f3541d2894032f284098f147a2d6eabed6a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0b2db035cacd604cdc344f3200e33d8be8d2e6dcf40d18e60a1d3de7c6195a37"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0021c921219cc9741dc3ffecccfb9e63b48de7f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a234034f7bfdc7d426d79b5f7fad8436ab5325c1c7a1712a077321c460bbc70a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df20f9c143ec7f8391e7bd1e2ac6e1eb6d2e56fb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "01c3d9de3fce9deb6913db065d0ba7e1ab2641cdd080702e7570be1431396eb5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "aab119d7ff24a31dadf99e12e5c22ad5b9e65159"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "20dfdf25c7532d61a062c55e36b51f9a0aa8b7b635f16303736e6a36fac6acb4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c24a031f755400c0cb1d06ccbba3ce4db2c2fe4c"
os = "windows"

    [[PROJ.download]]
    sha256 = "37e9136569bebb24c97abfbb1588690bf4f888576962d9f8e57ac083efce291c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6427588b1ac80e3de78e0e299ebb0181a640c5a8"
os = "windows"

    [[PROJ.download]]
    sha256 = "d0915be57b8415949646ba3d8ba4502f3cc86eeb8b1a4c8b1066c2ef78ec0d14"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.100+1/PROJ.v900.0.100.x86_64-w64-mingw32-cxx11.tar.gz"
