[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b43b9d9ae13c09f1bb57d2511af827bf6f6521b6"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9203dd952c9947c8683d1e823357e95e39e3be7ae499b8fc1bad91a16000347b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d1f31b1b18d914f47aee2533bddf6937cc336ae"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "38b5672c8e74da14cfef8f539ea14df3992e8c15af07e12d9df5ad08867fa73d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9176b1fda7156c12ffe2dddf808696f4b403b58"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "02b07c463b24ea5aa5d5684fa69200cf3f4f293ab90217fa79d0f1927b9b868e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f5104070c92b4a00d1327db86237c261c2874c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "d7d3a8a036a053f8adba18a61084313cf19b249f70f5039e6c308dfa9e9f6219"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19997488765e7d3a5f76e95f3cdd9e0e9a0edf25"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2a524e19d48c9d6db9976120a8add7cef3aefbe3997279d12116131ece5c41de"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1d584dca467c3c84ba70281e5c85c1324faf59d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a668debddb2e2fce1d690cd1c0803f90adf936adecc95093479c151c8bb9365f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de512f8cdcc86e938317eed6f60ea8c209217f66"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3038ba807590e5424f6e2f752bdf45797fec5248ed7c465d1cec79b5961a8bb8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f1e3f2112f74b0bea2c4ffd9431c71c4cb5d741"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b475e86627b5a280fbb773737bc9b5e4d4fbf7a3a6eb3d0b1cbb53a9bc6039f6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8280f7ad4325bc29927caf7df19b19b5de1a49c8"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "4cdb24ab78f0bdce8fcbb7d25786f1945fc15a94975ebeaffdf643ced6ece4ff"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0420d56294d7f60a6514437551f4fb1874c50064"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "90b19dc87213f34cfc17f0e41d994ead374364cf5708e2e57b38b1bc95d0cdcd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c6d59ca3873443deb9dd8528f352a545b74fee8"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "fd34f08d94f00bde5d5628cafb9294b8a84c7536c0515b375c17f52f093ba96a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d80716abe8a7055ced79b937fc4092285dcb88bd"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "657128406d3efd38a424201190ce9f4e0b2e9036ec5b4e260877ad585b80f30c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a5d92e6976fd47bc9256ce186a5e09e3e90818f"
os = "windows"

    [[PROJ.download]]
    sha256 = "c6698344681cdc37a75d29217aa3c44cd1e53d166693a5e821bd33f805520b1d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96d27a62a1d564b77c3cdc95ea3fca3f56bde3a4"
os = "windows"

    [[PROJ.download]]
    sha256 = "624f25a38e4ef5ef58ff992b3428c65a8c9c42d320c0207e6c6f2713380891cc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97ccf0cfefe4d425ee4d3258d5571e06ac11bbe8"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7b0df01689e5bf76344874eec077d1280f4ae53a415e036684bab892055b97cd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa9c4a7eda4da1ab47297afeebcdc9c4babc10a3"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "8cdab5da21d9641f4d0bd2263595e93fcb7cd12a0184568a5a74f3c1e347edaf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "20a1d3e9125f01d5a682344dab8067dd4892a888"
os = "macos"

    [[PROJ.download]]
    sha256 = "3694a1f62807f709610087f180b22db2f8f61bb54e3c5a7f33dca6ebece7a6d2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb711c5d887cd9a5fc4b0003fc34bbbdef7c2b0b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b0f0e71a1483bc89034222d3c10da053962eaadd91ccc164e1fd41dd00ccd7c3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4042eebe8c85a049627cfccbe32a81a683f557f4"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e440c0422a5b4a1d2bf08d82c8c1c2783f0e2187c4d809d78379e8818e78df3c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f2bc0ce30f58a751af927f5154864993fd8141c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8f3808393bc1c8473c9f35165f148df0d596f11c3e255f5b604822ab4f478b0b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2a6f6b95d5f4a7fedd4c8c6830453ce21afabb5"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "85f5e07fcd32192e3df0f8c1ce2d53157e24e08b1812ecf963c9302ce5fc8f69"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "5dd7c57c40fccb95f7427de6f15f8df797f138af"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "fc7793aebe8a39b89687ce3de812d2f0f5c1572319b9293debb8445164f90f04"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20e32060cff5eedb2df2b65021f9e59e7c0895ce"
os = "windows"

    [[PROJ.download]]
    sha256 = "ffd448c0fbfcb5bba84e11b6acbcab6c359669e995152c35ea96f96c55ad85fb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b827c9d6fcb7b9f25ede8cf20fcbcab2a497200"
os = "windows"

    [[PROJ.download]]
    sha256 = "2b015fd74f47666bc55286ad8d058f829b7034f549b5b89bbe8e8beaccdeca92"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.2.0+0/PROJ.v7.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
