[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "f835138202af3c406dc5d5825fcbd12f5f3a4dd9"
os = "macos"

    [[PROJ.download]]
    sha256 = "6a748e9ee9855e646b466b60b89e2f5a4a51aecffaf80098382c4f1ca73a5559"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14e5a1686bbc4b5b94382c519be7d99e81308fe1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "29ca667cbeaf2b3483615a830260e6ec175b9bba7e568b94189833a1df7e1664"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e16e972d3af3a03b35f5c97b29262a496efbfc7"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e50c16949ae63ffab9b0a156a13ad747c420a60b6f31e0a61f66371aa92c9682"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c080e0554d9b6d19fb00505fabe51a1a5d31e487"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "ba07515c95cc34189fd72425026bfb3473232748f6f0866e801a27ab0b6bf8db"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81405246ccb7607ecf8c69f768839cb9c2fc3e19"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4cb7d743bcffcb0446dba8a623ac2d50f1293e08c8ac0e1f2b10a4d2db92961a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfbece00a6d6d75c382ec9ce9548067cfd405851"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "da25af3fab9f9e30833e918285eb272d393caa5c8925699789187bcec7588bf1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d33ecdd3b4f86814aabd9d91ff40031311eb5399"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a8f29d1623636c273e0b1c6d509f5d512e8bdeaff8274e29f4c975edc56c5b85"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3293de48ec71dd453e77b12db52e120a2bd90535"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "da40eab2bc6f2b6056a2c158fc7fc13bfb9e7497f7b8da6061dba583938410e8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "479237edab303ad44fe018fcb52aa3177ab2d919"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "90c6c12256834fd547b4717e8f71f5cf092e611274dd9f486f5428afff2c6b5a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94792a8a073fae744399c4c325fed97dc9d8c1b5"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "558cba04043ef1aed7867fc8b6e97c8f8e79811174fb79b332ff69244db78de4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29e46fc97dc9e3adb30a8ff653bf58652dc90437"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "db13c44227d9131a2c29a540aebf7ce55e6e3f6acb19cb35752300479bd55f85"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd83dae8ab9db8225ba088438578a8d9977f66a9"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "2917cdfb201fc02084c2c5650bc3fa69d419473187140700dc1f9cba503b9430"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc10afe1f5b31fc6880b6d394ed3256bee01c0cd"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "c358790f3f05e1f731a36fd168cd72633a7e8f76681cf1f10d46337855359ab4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7f1d52426ee8af0317c497cea29db67a2c41af3"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f06ac99259bbd3d782d40f588387b0c14fb5ad3bc5a5a60e77821cbe97ca3974"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e721a996c8ffe7616ce25da9b1692bc6877ce419"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c3f3a1b960952bbf69811146af49ab3e4e20524accef1e96f179153438219369"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96ad2046463c58731aa789fcd26dfa6be8339318"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "619bd8b09034d5d77bcb26ee4e06cc0941aee408d62782d8f599e7fc2b632429"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "552b9fac51f0481d5c588190d5e5b19e568c403f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3564af10bf2390d00528b4e264ccf4807dd66c422a38c8a5913aae48b2297dc5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fc70ca6eeca77d4a6d84c19ac0b2c52948dbf3d"
os = "windows"

    [[PROJ.download]]
    sha256 = "deb39f88d3aaeccaa1d5a9ad9c316730d737492f6276e47335ca944fb04ae572"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25c8808ef6211c9a3b5336687ef6c65e9dd0462c"
os = "windows"

    [[PROJ.download]]
    sha256 = "346e405f5d7d6c9f7f95272258ac89d3e0e216e403dac1cc078c3e69751cbba5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "202536250f73b2fcfbae6f0ce52064b829d7847c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "263516de265ee43b2921c223941c8a73365330f87d08820411afa573e69afa61"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec5032bec6397ec2c47cc8a67cbefdd4a6f5b304"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b308fbceae9446c0333454dc2da860b922605f6db08afd2380c57a4844ea59ea"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "eeae20093cabb4fae307c6eeb3738165685202bf"
os = "macos"

    [[PROJ.download]]
    sha256 = "5fef6fbfdf687b529cae4bfb1a44807dbed0392e3aab0dc986567283a764ffaa"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "372d7d8f3d54d4dc50f902639f715e7788e3b512"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5c5ef545bd9948b35457af134b80ebd055a6edc2434f059704d802cc3af296ba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9b0b83f7cb35e76f9e8eec7e5ccfa821ec17dd0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "bf0794aa870d75e1c6e5c4177f6eb487a874afa9837a299779b4779435653472"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25c9ceafd027f943cdb53bd97ce076f3afcbc674"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1ae87a60d63222b7da1abf0e1fbe5e234e933c353f634b278fd0df4162db2925"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e15d2ab5c7c4eaa58b320ecfe45110da91cf5743"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8d0d3060b47d70a6da95895c92cf6e193602ff41c8807b6cb195399bd240449c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "7d853a433a8d5970674ba49da933d34cc9c74bc5"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "3a93942bbccd77c88ffc5aa74f334e040bccbf5c7e2b5d9d7fde8cf0c55b02b9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e94e437ecbca49d121ba2ae6a1e670499f809dc4"
os = "windows"

    [[PROJ.download]]
    sha256 = "b708dee5e681c2e67242e5815419a769c907f7b0d1b62ff2cb5b599bd46ae861"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63e23f0ab712fe1ce19a45bff22a98b6cfcd7d2b"
os = "windows"

    [[PROJ.download]]
    sha256 = "22e99bc5b937b6d37964150c1be7d52cd7ae1119cca79a9e98683e835d46c376"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.400.0+0/PROJ.v901.400.0.x86_64-w64-mingw32-cxx11.tar.gz"
