[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "9c18402c4aee203e660fb0bb215b555534a72c70"
os = "macos"

    [[PROJ.download]]
    sha256 = "d042e20d60731cb22243aa027f92e19fea73296f20e480e2ec492d51de9e869a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b130bcb9a782d72a7c51a470de0cf5fb24902534"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6e2209ff77af8badb1e8dca86c328f033cc6244fe59b33c8bf7d5f7c725b4c25"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dc6f73185aa6e2ff29cba5ff535b00d32760eda"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "51d92c1fa13f84b4cb26b060bf84fbf4091fb9a11ff02090483a00dd155aea83"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b454ff2521c668441f7c7a7600e73b50a0c925f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cd0b93d99bb9caa3099f8b659a28db2fed4233a360b0f4c67b851bd9bb1dd660"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5059ac5b0bc5803325c9361af97a7e4f45ccee"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3aaf0d5d9e299d6c64cd900e032cd286b79f9a49df9af5647cf64c584b954319"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "98e839a7a16d1f0026cc8c78ec2a7cc7bc28fc4c"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "b48fc761c33fa22321582d4f5c5ffccb81131728ea425e57075e9c9780da428a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.aarch64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "837a0f61d354187bd3957b2fa2589702984c6634"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7905f5d4ce1d63ab0a840eb2d6d702bc27ddbe774009787d6c1f97da0c33f51a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54e7e65a4a2366939e15b88fb30e3616137d050a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "450c08572341ca741f40dfc8ab50e0f686cfb0b40bf405be531bbc2d07a73e21"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44787e7f3681f490806ac8e10ed6e8f3b1aabcb7"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "fe3f91855e3c40421b84539a33a8cc2c26dc478edfb9051247bae181f71dc2e7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fda766fd0747dc916d22a1e4dd50fbc0f75b50a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0de810e769cfd98d6f89be96dde002337f0274578dd6ebd877bcd0694e82b582"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6acb672683af76d3ff2211edd44c7ba1ad9f8487"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5e5af74c5e7724eab0596e9992cda288d9446675492764cca159f2e14a7f3496"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3aa5f3c865aa9af3b916580735d2665d894a900"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "100ad1a22070c065339ae2ee33e9f07e3815b7d67472883f9921dfe5e3814c7a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b3e7e3ad244fa4c9f9d67cf89c8ad9c11fff576"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0ca30e73808ed94dff34981b11f04dc11933d56b586c2ef4e60cf357ffd603ba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cbf79b294fcff3454de983be98e07a66f7fe014"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "bf45a0a1851e0c696163312e0976a7b20584aa7d52420ed1b9722b7292a580d2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f652fd78f259b5373d0fd344e050a2d306a0cc3d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6e7251b6670fd1c9eb92acffbe4c737e734605e4a3c4a265eaa93e1034b3ff81"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cfd299e253a802c97e6e7d799d9bb0cb510918a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f53ee887753ed5685f4ce8e2a7c895f39484b6beca91d5898f2e1a92729a63bd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "314a79af37374bf41182d2861cf61d3609b9d763"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "65f4e65d9992ad27612bcda86aca4b30e38a1270a4cbcce1c1c00f7a103dc89d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b439c9ad3fe27ec9fd58ee69bf4a32a191d4112b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "212216a5120abcf53de3cef962179d9495f2e3ab521d9bccb6d857b5cf2a622c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43ac5a6345c91a9223f1258ca2a72101f6981306"
os = "windows"

    [[PROJ.download]]
    sha256 = "0314f40a4dcafc125b11d96cbc5381ea4afbc0e87cb8a28b860f57af9fce8954"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e5c0b74791029a4e5ff3f417d3d3610a5b87db4"
os = "windows"

    [[PROJ.download]]
    sha256 = "5c17004961c98aec52f3238b39b907a712e76cc6c55edfb5e8a241246db47b5e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c818e627de4973305551d060c034f26e5267328e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2c45d884e446fc227accc820b26169da27c6c56093345ba2f64e7b9caa0362d0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62f5209f8636e1acaab1f6192e5d3707e77caac9"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "8c61d62fa6f37c889ca0817cd116c789b9ae3609ee31d494b4b799f8414817d3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63d92da75df7ac93c5ecf23ffa609c64775835de"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "eea97a39618e8a9fd0a32ff04a2afb822974be4697cc9b65b0e364fa7a51eb26"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.riscv64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dcd4d960b15deabd49461bfb7fd6edc4579271c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "ff19f112476b278489993b5a377f0f7d844ae1744353c74e0e3d1655593a2385"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.riscv64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "2a6a310b6e79c859d37f76c3f6d1399c822954c3"
os = "macos"

    [[PROJ.download]]
    sha256 = "af1498279bba46c902f791c50f5acd51e6d2ab0a1ae8d39c6380e036a404ab58"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b19e138a195eeb1d7eb0d86a7c2117046b572e72"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0d0e0d92907be9756fc4431a5b08494e533017a044ebe79521ff4ea936bb93ee"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87dc7df7131c231fa48dca0cb94e54ea3feb2c4b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "178816862cc701f4a5262e5592d7ac09d609e46381d76491d2eeef7c94f3720c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbdf469e45811bdb9b63ca243ddcfd3f479b084c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a791dc5ffb2e154ce1a835af2772b6f907d81aeee5c6ed08bba5659acf87c093"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dedd848edda72c334e1e19c3350c760b0f30f5a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "794a4082d692634ae7f9de90aed6e3f37f44607d7a576ef035e2d9924236cba9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "9158ed3e0b32993c559ea14c6b16b1317b8db0ac"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "2962d1f53dd2c0644f180dc712016572b7c06ee40b0f70029cb0c0fce436625e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd9a07e2e5f203f554e76ae0a2d90f8517f4fb3c"
os = "windows"

    [[PROJ.download]]
    sha256 = "5e205361d8c66fbde93e8dc277850458fbfcf8352de139552664aa1b593f98ad"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46ad5240c23b16b3d1ec2f6ece1bed5e8a7b479f"
os = "windows"

    [[PROJ.download]]
    sha256 = "db8ce1503fc843d8fb8a4bcc09c4db46e5f84e39647ec2aafabf9b27f65fef0f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.600.0+0/PROJ.v902.600.0.x86_64-w64-mingw32-cxx11.tar.gz"
