[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "71f842209dc88269523ab21f38b8696ed4039b5b"
os = "macos"

    [[PROJ.download]]
    sha256 = "d7291a7045e38b29638a3c2fe4d62234bd5a26bfcb98947eebdb0396cead7728"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bd8dce865a4b2b08e77cd109576811d7190803f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "065af35994438032a34ff9e208477814431795d58cca11596c785b210f7083b2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "482a6a93989beb2fd91f93ed22ec54975eadbe98"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "d302ccd35534a28a8d2b8c467f907814ddb0aaa6281dc06c5755db54405c1ad8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "2adb860ac13e65c795c3e3c9bd37858a26033c92"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "03a8e0baed247cd251253c46623acbbfde8074ea25fcef89718e6a586d3afc84"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.aarch64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8f203b1e376ba37f9e5e47076c283ff3c53a5c2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "78b0e5b589730ebc705299b60bf4a8b0caea6b90078afbc60f618bef52149b73"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72346a8fc646dadc480c3f4f56b0a8aadb935171"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "d1a637db7df42eb9ddd704edcb390c67734beda22fe22248d7e5915a3a670275"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6710842a4334ab58c43d32f98385e6170bb35e9f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "332851cc066a0b9c2734fb613085af89fd3beb2a6cc4c8b43b3dd46a6be86504"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f42c2bb66d1ac0cf5d01e10aa6acec05a6ac1c7"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "706e79b7164291b643a6e3cb3547530ea464f0f4633963d104f608b69e779524"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f56e3f3eb1681a8643736a58a7eacdc457bd9fb0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9ecb3271fb18937f847f0843ef42c4cc1e1cf4ea01a4938ea4c7e93ff6714d4e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b10ee0d50d4ede98f64fdd70b10ff7951871ca15"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "2071e8f40083016324ec1e8b82251b4ef060c9081ebdf3fa6de40d9e1f96c045"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8a9f29bc95fc2a45ac6eae209353fe9b11b72da"
os = "windows"

    [[PROJ.download]]
    sha256 = "961847e409d44b54c6c7b38f1140e017782c932c63d9b0d0a6c0675427c3bcfd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1760bbdaabff391f64c0c20c832066a474f49a81"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0514b4cd9f00267dea338f98bbab5c82e58eb7bea4ea2a8e8eff9f20abc0ac36"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6907a83de3bca363b4468da08969d686aab9217d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f6b9a2d3d39fc32d73911df18c2a56aef04923595d4285f7f1a439e7f937aff6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.riscv64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "cf4a3c459f2fe6f62bd41322327685a66076f7e0"
os = "macos"

    [[PROJ.download]]
    sha256 = "5c0d2db1b26db81dba3b4be60f42482efe68ab31c568fbae9272fa700a2bad92"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f6c3eecc94afdb65742f3d7206c82dd76d692a8"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "3ac39cfaabd12dd6ae0edcefc593e39568b7c2b5ecf1355e03bc2fcfaa3cc8be"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5e9cdcb022bf416d8f66d0f8543d22fa08bdd38"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "73c908c974ee16b7716543eda411d46ab891ab177b0182c7a5600da8ff0b5e4f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "2dd31a7b279b97f6dc6561dbc4b315f79ed1b20c"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "8f33d5d993a50cad66157d8a1ab462a9be20694860e0c1a214885047da55f687"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a20eb159fb471a1ea0aacadb3dae5d52a4a777a9"
os = "windows"

    [[PROJ.download]]
    sha256 = "9c3ed65182af2152f5bd7fecb2a4ea2df16001dba4178b88db0fc26b928af08f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v902.700.100+0/PROJ.v902.700.100.x86_64-w64-mingw32-cxx11.tar.gz"
