[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "82969ba1aac8d15180fb63a95f52329c1c77f4db"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "6f56c5c2479e633961c4180280f2797377e26f4e3b7c87c67421fd7ce0181f65"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.x86_64-linux-musl.tar.gz"
[[PROJ]]
arch = "i686"
git-tree-sha1 = "1e920ff075b73783bf435b27381bbf4c3e92f668"
os = "windows"

    [[PROJ.download]]
    sha256 = "f840ef2fcb6bdaf7d32d9f216573410abec36f0939425ac41070a23a2dc1d0c3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.i686-w64-mingw32.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "63eb949ae2b107bf258e2a838dbcb05c8daa24b1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0a3cde9c14008ee2c1a50fc4c216fd882da1ba1ecbc3826a3a75afae8618f0eb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.x86_64-linux-gnu.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "ced03cb43f50c3fddddb18ee67565c85b5383d21"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2d70f1feee634a55a61a3a23377bd239b446607d93f263481a6ba6f4e4d70797"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.aarch64-linux-gnu.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "7eeec1c09dfb7f934eabe620ec6488b4084d8b5e"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "8211f12c27819f9ecdbaa42c3ee49b321792b27692d671869228ca502525f79b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.x86_64-unknown-freebsd11.1.tar.gz"
[[PROJ]]
arch = "armv7l"
git-tree-sha1 = "d22641d5bb8b2ee6828adcd50cbbed5906ba5ffb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "828aa74077ff2b64fb67ecced37cb2cca4cb735de2931f917eec3663bae5b70e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.arm-linux-musleabihf.tar.gz"
[[PROJ]]
arch = "powerpc64le"
git-tree-sha1 = "ee62cc6d5c85b7ffd0e5f595e47951d27336d71a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0c11987cf501c95011eac221f02c863c6e6559e051cbca06f5b6054d9dcb59de"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.powerpc64le-linux-gnu.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "6748468c24f2ff7f894c80732699860be9304ca1"
os = "windows"

    [[PROJ.download]]
    sha256 = "2acdc59c089201816dcd70d7895dff0840d89de4c55c016e1442652756a5383b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.x86_64-w64-mingw32.tar.gz"
[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "5e91b1e4d611ee982bdf36294a744eef67d14371"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8312c3341ec3fc70a6b27fd8ba90fc2785bffc9013e120fc92ba46a54e27afd5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.aarch64-linux-musl.tar.gz"
[[PROJ]]
arch = "i686"
git-tree-sha1 = "74dbe3391f258e4d80ae4c6d7dd3d51e9e3a853c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "91d2d702dae26432dca726121451ec65138a44aa2deed9b5028b4bb3b3f0fd57"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.i686-linux-gnu.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "17c0c1777a891fa2641ec8ea8e2130518a783f05"
os = "macos"

    [[PROJ.download]]
    sha256 = "95994a01661864c688cc5f629d9398552127dd95cd724430a989da7f7075fbf6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.x86_64-apple-darwin14.tar.gz"
[[PROJ]]
arch = "armv7l"
git-tree-sha1 = "5dd8954613cac801d7715601b7056dd66960b8dc"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e9586b87de6ec93f8584ef8e6e39935ccbb073216420249032371eabd8ded481"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.arm-linux-gnueabihf.tar.gz"
[[PROJ]]
arch = "i686"
git-tree-sha1 = "0eb39c00f72396cb5bfaac73d5fcdfb9db33f075"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8822972379f0cdb29921bc81a80d75e5f0d2e6a231e15e5e5352f043b9761789"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.2.1+0/PROJ.v6.2.1.i686-linux-musl.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "249aa4f4331d4f7e97582b86905336dd574136ad"
os = "windows"

    [[PROJ.download]]
    sha256 = "5df75b0ff6e2b05a7d88309412a34677d0bed9fc0b9ec78a2c163a5e264face3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "189c6fbd73ad6a44924afb2e154f7188874214e1"
os = "windows"

    [[PROJ.download]]
    sha256 = "6105193fa8df0ed6d42d90a91f346006f54c710c554e832df30438e2f6bf8994"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49428919940ff8fd6ec863a733f728bf268d436f"
os = "windows"

    [[PROJ.download]]
    sha256 = "0ea39d22751d7cebf0e8f357f2e2bf59f0c4156804c92222300c9fad046723fb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fcfc4e713271aac41c5c29b5a99adc7f1028aca"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "8e82b7c801f3f49974dda634799777cb78ba7f4bb2db8f6c9f2f5f1ed5b0d49b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cda62fd40d348e883f0f3c45cfb78f197fb37470"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "dd09eff0139f4c7fc978170ad7a14b9e0e700bc92825e6e71ac21a162c8f4692"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2697c4ac189fa4055999620b315722126485eeeb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "7e5ed0dedda02375737393e543f09835d13454d58d2e7fcba69c37114fbc24e8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41d7c17fe2a6d7ea4a35701ec21db8d0ac005efd"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "4eb92280ef15c59acfe6367b991049ed7b58f77879e4a28674fe3f526f32b08b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbe00956dd6220442a3c3cae5991a831af5fe0b1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "67b4e528cc70ad1ab6d94bbdc0178789ae9b85097f786634a542cac945d76bba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.arm-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7972aab48b623c77c114164489f2e93fb8d0d7a5"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "9ae1221d3bfc35830ac62877a651c67689c351ca314dd0c3f49d36a8305f611b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8233eeb91fa73c19775b4b4729c526d6f225381"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "cc477672a87a88870b38906052699c106dfc2429e87602dd17385e30d2a0e46f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "665d7c90f085e7c42ba0d870ede5242a7f85cf2d"
os = "windows"

    [[PROJ.download]]
    sha256 = "75ca465649ba3fe9edd0e1313fe5483d698d2bf53bc9368d37e9bd36792974f9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d05f6690693864f434cc8302997e2b2426f3358"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7743c3935bf1ffcf24f46f6486d17ce9136521d306091635483ba9bb2318c632"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.arm-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5413575e2332d442b6a076a689520a543ed9f96"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0e46988cb74f7b0859c2d5e9bf7e7593df7f47e714d39e37ddfb7487f44f92b8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad290f687f3662c0fb6e0fb7f5ed20be55f96470"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c70c326bbbbeb47c8c8b23123424b7be3b801c6b4484541a1dcf23aac62f4f62"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bd95c48fd339282b18080122ab2471be787c2f1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4fc0ace099777c770afd1cbf9a1221fd1c55e102446d5c60086a2ac6d23b3e4d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.arm-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f0e1cd3aa77f658f98d2db545740ad75a782355"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7886de014167c1f5d43d9a1081bb3afb881b1f839ec9dd9202fc787c56148d46"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a181dd0f9226aa449d19de65b4abf9d4d99b19d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "4cf5d4df490c3668b9b89e561effd8b31fcd01488f367afceace30c0cc6e97bb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99a9b1afb6e12fa04431f1fdc9b1f26bef374966"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "46fb0bd5b8189b96456d695942f5eca023af0e55bf2b7a0aeda736d6dd1e75d4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13429bf356486b5c8bec9b5998a7594e6e7e90fc"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4d6cea238a4c7f05809befc17e6c5a57e4726fac5253d908952fa687475b706b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b2d49e29d786e643f3e5ea57c13e420bde68fd1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9634ebc9aa06752ebc250fc21399137e5e92aef8a7d3c1f89b42b24c2cb02b53"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c94e50f9cb9d41ce738c2e6a750ee9ed81081c8b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "41b7e7f97eb9a64daa010f807e68398e8187eefcb7e898a8d65c0b1a3a06454c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "048aa630357c864ae80500b4dafa9ce124619e9c"
os = "macos"

    [[PROJ.download]]
    sha256 = "e832f050134fb0dda14ea5d06d909db48bf8b88e88ff3a0587edc9d190e4fc67"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fd41ded0bb98e8dbd96ebeef5928d2991f24dfa"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "10358b7d795ffd0586db7013cbbcdfdfc54e465e67530f93b398075aab2ef820"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5af4375edd2a9ef121586daf2d6cc048c495e354"
os = "macos"

    [[PROJ.download]]
    sha256 = "c1eabb6cb50488082a59542d47901376e74d77b4b9726a1206122941d896cbd7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ff5ed5778079ee9ecbfb5420f3c9530cb40be3a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9d4ce37ae7d1517af07657557d4fd5283b746d3201a40bb82a8eca4cd042aecf"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.arm-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25fe442e74f4071c904e52d47e579d43351197c9"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "5a26fb060da84eaf3d6a75e1e55eeeb10eb80fbfa54552a3435d3169216bb9e5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.0+0/PROJ.v6.3.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
