[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "1f08b13520c225194c3cb9254d575a29efd32491"
os = "macos"

    [[PROJ.download]]
    sha256 = "a173252d3203bc6c0b3894a32b703f93e2f0200bad87652aef8e34539e7e9823"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4931eb44e329481e985ae89fc4da8af6d7579ad0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5567123583e7220c1b87954e835c142d4113e47105c4cee7138f56a9abdef98c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb3d540b858bd9e8326ebda6aede1a94bcab7763"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "aa7086982f6574452ec754234f29974f6616769fb431651470b99f7e06eeb258"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fc641e293d2d671d530f3c41eeb8d3a4828e9e8"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4d8dc03ab8faf800b0b687e367a160b77e719496f2b5d9652ac64c5dd2d8bd1d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aea0417c304e17a4ba58aa7d6ce1ace3e3c1a1c6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "ff3492ec748227a40b2597ea8fbd691413d5c6f5a00b2dadcf273eaa12dc395d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67fe56c6edf017ffe1d04dc9e598f956cbde1e72"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "620283df4fb95240e5bb5704c6a422e87a4a14e873219f73214bca5e49bc745f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27806b2505c54c6a5117881fd17bd9a65b94cdaa"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "35428eeeed6e2d2fa9ace113fe81f5e043d161b123bb5cbc1e80f27dd452980e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c6dccc6d18abccde39d9dc2a596f3ac909b306e"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0e10c3f95bac026d3816086f8dfd836002e874d5a22a09393eef7abd70743100"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eee53661b8f1773ebefe93f0da8fec33c810c43"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "89209bdc7288678feab975e1331abf32a28b1390e6982b726739fc95fca45988"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8369b36c2ff6fd215577b1cc2b2957192bd10a22"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "ffeb5526b61eef248831624f90b082a049d8828037be9ec42b36a3e0385e6339"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9595fc400fcc7bcf4f7a457b583af5bdeeb3aebc"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b8ac8b522c62565ba3363ed4463d086ab47383b8af1011d9e191086f181bc59d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b4482dc24eb55000c705b3d55b42e68504056d6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "975e1320bd76c4bcc8764c89f5cec39aeb19ebcab11c03b2802c995e6fd9e4ea"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "586aa68aab0784844ea6f7b558048d1a35bf68fe"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "36f8e2d5681b1bfeae43768ac640d3cac062fffa66159c1b4e55ae93b358154a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6dea0ba1f020151d90d28bb308212299b5a0561"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "73e803873a775e1b086adf30b465d07eafe966f32cd33f422640d4d71d90411f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab4e94d2dd84bcc8963754a8a67dbac093c53158"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "b19a7691b93ab17a7cdcae592aa5d84d948c373d06bb29848ec320b43714857a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aadcb8d4ee98535fe67881d4571073f1c4808ce1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b91befa3d5b654336b2c8f68c4a780f5009289fbd02e015e681324f872e9349e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0539b722eb632db720a58f09b2421291ee3e88"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1d54b28a0b505736b3d8aef7e62ab629278c70bab1f8979131f2d78baf02a0d2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "603ad626a2d4abbca298c8cc5223ccaf4c8e26a3"
os = "windows"

    [[PROJ.download]]
    sha256 = "f40a473756f0f5482b6e2d09426d7cb26ac67a2c725d32913e7e60234ad67d50"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a4ab98b227e639c0422dabbc541a8ecacce9ade"
os = "windows"

    [[PROJ.download]]
    sha256 = "82eaf2c7e5a4eeab9d6a30a0efea0c3521371830bdde0d3cd9d1d9ce52eb846b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af6b63a421d2be23acfd37beb635bbf20a703465"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "ecbaaf04dd6b7b0d080131e0c4ae1c2d02322b8d4c2caf1eeab633ac5878f640"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105c039e9d007a414e3978ded31d0e217cd1a397"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "cf73690c6ece7c897a1e6ad1543bdcc68c52fe58382798e6c8caab8edd3c1f6b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "46356c6caccd3f5662eee068cc9cff73627a1edf"
os = "macos"

    [[PROJ.download]]
    sha256 = "31afb756567f57dd4416697593fe60439b9140637d6371c83b6cb83f48ceb2a8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ceba5ffc104ffd7759a1bcdbcace360501ae26f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d5390dfe8e724995a9ea92fd80a286220d46c8111a7c45a6db0e649c3feb8bc2"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39b4e2e086246249aab83e095418d0d15f4554e4"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "4f23ae01130d9c1c4118a6bf6150598adc7b1acaec8357eca290adb476d00573"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42b52d669bfbee903e7f88263dc75366d2d2b269"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1f24c39d473cf07bbde5ace836bfa492da33aded142857fd288cd30b8fbe01b9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1700bd6ca81b569ff94a231c671862386d267cc"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "2b30dd27d9b106d6fc8a9ae6088ade171a725cf8353c5934d3e3236d3dd8d4d4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "ee23844e654a9d56264bcdc421e91334fcaa72c0"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "ce64774de69fa4f8a976b6ab99411f869775b4021a864ecb3fea92f8453af715"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee71f324ee9ddacc3e249cba627ee0391cb24cdb"
os = "windows"

    [[PROJ.download]]
    sha256 = "50982bb292e9acc13807c8e2c01c356755c1bdaeac4a557b8ea62d955a3ab1eb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c592fa8c3dc41354aabe24af9974bea116607227"
os = "windows"

    [[PROJ.download]]
    sha256 = "5d46859a5e2298d9e3e43c5427212db2fa7d4638406861ab87c35a459fda6844"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v900.0.0+0/PROJ.v900.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
