[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "31afa3a96e3ed6959db5709166868d8df208bcb8"
os = "macos"

    [[PROJ.download]]
    sha256 = "80bb4ce8cdb66eb4fe0544eb1b2bc663ee083d13bada101a8a6ff68ac92be4bd"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6007968f441da73d378f24aecba3625b33d72cd3"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7a6853f48504f0dccd326175489c5da59d70e3071b1ae0da0349e650d4085687"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5c8c9610294d4b64d24792b1608e8aac7690e14"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "60f8199681c91f60cd532e49a8433264052a05bc2f33ebb9d1029aac9ec8e210"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c24c8c9c14b3d4216192d59c2bb0927229e7bcff"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8e293749796c56168dbbaba1fba6e20d66bcc9e17818f8cd3256ced3ec4a5aba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfa71116b3702937c18dfcef27afae99d9fb927b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "bf2e5bc49cb720f72091e67370a0bbdf212868f7d0c1f7aea5c396bee32331ec"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bc48e773b4c3530ca2acc53db454ef5bcccd104"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "90df4bed2c4e8118b83c342c27d7127da60f8604087d8da132bbe80d6b1701ed"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26bdf88407fac0653afdd588e71a54531901742d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0608c39531c3ac8a33d9ad0991ad9eacc6c719ce7a0ae5e6bf2a172311bbec94"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "727dbe3de295df52b1749c3b2b4e5652fa0e7cd3"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "bf6da727cd01479414a75c031d925af37e08f31fd05b1d395323206b48c6105a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e89e2bafd27e4eda11e286877c4431cb0d26c690"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0c2420f1c04c46eda2350145925c58ef8dd9072b878bb2d4cc89a54b7cba9e7e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d90d9007ff233fd42c0dd1b861278d52fce4e3c6"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "43087a01639dd37effa22fd3aaec352b0cf7375ccff2f38e312eb6cb3fbeb4a3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46145d0a6b6a1e9136cabcefeb1347a834df491e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "53bc80731cea8e01e4e05ec6b768da0e5169c27c8d960d223461b39dfca118ba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e3e41b2ff54d3b7c2ac68fa9bd15858284094ba"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "afea3f64e30f3969bc23309a1fcad7716f19ef8eaf5127f42da375c426fedde5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44bd8ae5594557e572b002feafe84edc90e25a0f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e07c7680d457a8b4e7df5ebbb72d34e2dfa313318fe9db7a3a851a2e99b322f8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80f9400f5cbc7a39c45b2d1e6515c3f81bb7aa36"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9d073f1fd68344ae30b882ea76241f91f8845ffa08c677377a8850ae3dfd26c7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aeeb0770b3daafa4b384f7d61030dd8e2a3fa17a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "151989bc52ea01874d625bceee2045e439b0281dfd2a3dcac7ed59bc74884f08"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff32370fec0e03d8f1e05d5c2f0d07ab67d1ac3c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "984543293f456d79a7fd7e56901afcc2524cc6588a9d38c41c1330283f4de090"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c461a205f669a20a81cb506d308f9c894eff0249"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8cd76682f3a326dc938db7cb63bfd75768d59c63a66f1cfd56fdeb778c141e66"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15ba69be28953c1805ab92f0d42282ffee65dab1"
os = "windows"

    [[PROJ.download]]
    sha256 = "3d78f0728b91d8a211b8c078a70cbd3c5994a47ee46a5fccbf99673b7c8a30c9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86efbcd59507f9a165cdee0c08387cb925e030d0"
os = "windows"

    [[PROJ.download]]
    sha256 = "ebdee8e67aad5252e9c99eb71815f0c8b1efdcfdf0879ac1be2086bbdb357831"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a9b59e5b4c742fb17f75834f8044b9cf519e01a"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "386d42dc3dc163c32aa9b870ea029c398a0aee93af1766fd0c71722946f1548e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb87c6fdc15d1e29f4dbfe937b4e265735326acf"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "402d84f1b4c812ced4da269987b235d6aa417d9f9ba855e159a0789aa5ac7cba"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "8efd3d0c05e231c38bbc4b51b0f3f246bb115872"
os = "macos"

    [[PROJ.download]]
    sha256 = "fbe2a2aa76901886fd7a87d09d9eabc06f29f03aba02bf19ee0dbf9d95b44192"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b79393481caec3a6c762f88aabea1a29fcc4d6b3"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d461a9d02e66fc76ce024e30ea8ef1dc2eebcd5b3520776b74dbe9890ad889ff"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9c7077b171cb81058f8b509f53be09b0d56fe5f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9183b1d41a331d8ff93fb2d02dac9eb47389e7e55f756fb318e80489af015ebe"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff51d4179ff7be9c21643ebc290daf713f24a51f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f7711b51391b0811e9c230129401a8b445af4c74bdbd29995139d9ebde147e5d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8394a1decac93d9a0a0542807a9c332d737a6740"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "e919dcd4e721047e70e9208a6879ce1b00680a10ffde4a3b12c0d2cda874445c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "3ba5fa6f9b29e20781d67ea45ec087fe0cb0b15b"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "34b782d6fe018d942cf44cf833692058c186c19dce24ab930014eb5d3a4b03c1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a71a3eae02caf0e34a252eefcbcade82a1f34598"
os = "windows"

    [[PROJ.download]]
    sha256 = "398a6b0d9b8cb7a5d519822c4c3604e1a87e88cd560f44b55329db91c20f0d42"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78e35bf4b89312ca205a2e3d7eb2c63ce1fa5630"
os = "windows"

    [[PROJ.download]]
    sha256 = "740a254fa1ac33b4a9c5193e458390f3dae55ce9af82ce22b9ac07e979cf7ccb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v901.300.0+0/PROJ.v901.300.0.x86_64-w64-mingw32-cxx11.tar.gz"
