[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d52606910c57097080bb3a44f1dd83879680dbe"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "375d20b3e660a4efd3dcd0f4993ae507bbdc2e4352b99b5b5b8ec18144697959"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "825cc35dd98814addbfcf017d0afa908bb59f6c6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4f8fb2b39ca31819c569b2f8ea0de13e1a5fe8450a64f424b1e6bf14a9be3d82"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92b40deb4a0f2684c51ec53c7383ce562be18ab9"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "55c097a9e1904f857f73c80f6fccbef6c30d84af0f3ad2cf9ca1e429ae44a366"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4743cdd89e8f7be84c0012fb1f5b139d5075cf9e"
os = "windows"

    [[PROJ.download]]
    sha256 = "507a8634e918f8eda506d59e66dd3885037b6f8d276e0ff3474e79bee40847a3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0d19929ba2c7431e43c6f959ce7e43a64513caf"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8f4cb2c2e685a3bdd477a61285524230a7e3e324bd802af14754312e601947a9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b994a64d8cd9be054fcdda15eb187e7415598f02"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "5f8d391ea7508cec078ad8f2b70a3641b79a2e58cb5f33c40abf7b14b6381dd3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19dbc37a7535791322fff94f3a818d331e65d835"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c1b258e9c69c1dbe171af6449e144c7d17e35edd08cd1a1c90ca907fce2e10fb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a14e319ee4385fa3c8f1bb10f8981eecc9625dd9"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e8108feb96f3ca646b641806e2124f03e271bad9f2c941e5a5131eebd507fc87"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7f214caa56783c0ae97f8be718dec611de180c1"
os = "macos"

    [[PROJ.download]]
    sha256 = "fd688f73311db6ca45c7d9f55eedf2351c72b188b64df9ee2e5c2e93ad8c0105"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "950b640e4da28134053122588e9513ddc92f9d3f"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "0e06198378e2466beda1b4749ddc6123a4a11a0c00fcdaa487e7c4957778f3fb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da2e08b1f41eda474a08697d9c1addca7d7f6976"
os = "windows"

    [[PROJ.download]]
    sha256 = "d4145a0b9a579acf869f17126f5c4fb330f19734556a90d9b289a1af410fc538"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0896d7ece43eb82db63576fd6588d143c00e586e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "59783dc386310769b89949848a898564c1c181bc7018f6f50565fab02f90dcd1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f123db32d1c10a3a6f0f306ff1816aeae48a791"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "503e47623a1d0000bf62f2a15ab9101f448666a5769d77fc7e833930e6ef0b0b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e10c8933fc0e25e0a6981e20f6e17c0ca9efbac"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5e584fd3c2e5a551809dd8c8284a3c049a5c2c68c67f348cfdd5ff0e501b6a93"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7db758d542c0bfd478a61c4ebed4b1ea08cf1c4"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "2d15aa9d7c3b57751074aaaab9c509e50f0ac3a0abc6f647b9cc7a91447a2682"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f78293c8c0918a5e7ccffa526b7fe9c38bb0d3af"
os = "macos"

    [[PROJ.download]]
    sha256 = "fdc76c27add27a121b74ea96e2b07661700a9c23273a23a2050d2333bfc6a51a"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f054a9235a00746ec24da013e53e6ae9fd13295"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "9761ff9465de324517739a4455f4d8e9d2feaf3b8687fa148383f3bbbdf2499c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4a092ec79875924e374c418ed70d7a4f8869588"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c2a699709e714198cc1f86f8ac419b0ca191488b693bea6385b34f37752ed059"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c984b554243f5e7ee497620661d34eb05d9c54e"
os = "windows"

    [[PROJ.download]]
    sha256 = "97a8110401e52f646951b49ae892b17ec74508cb3f5b24059a5ae652a2a91588"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b66d0a44f4ef227df009304b3197c1b24b771b1"
os = "windows"

    [[PROJ.download]]
    sha256 = "2ce73e1fd600c8692c5ad2944013c394432f2fa5acf76c69b94de99021b75725"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97447952c80648127a82d2743bf0a8a1fad7097a"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a3c5a8ea37851a47a737945686c76aa98dc44157adebb8eb0c29b7e3592b6a93"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3711a2d181af5ad23d135e18556f3d1b7a404f84"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "16baefaa0ba443986b9bbc94c2e1cf2bdc09a18d36ccf9369553d4495b40e388"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cf600e1eeeda69a2c9de3a1b26a825952410d80"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6a3f05988d583397f05fa960a78d98cbc2d2cefe6544ab99a4b96b1dc3f372b1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "522eb74e246e71c2d6092f9cef4fc47187a8b485"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d922bcd6bd963e24ea56a532a6e2e841ab04de0c6c7bf7cad233ee912e94c413"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2af2d31c560935d865843a1d51cd4f19d3a96299"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "31b990d67e7aaf83fdf9c919316e46a33b030a5cec44f1739b12192c010422d7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fffcc0ab9085f40bb5f7318c8e06fb40c949ce5"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "c4fe3182be7e4c4b090d1950a4293a340fdd2a89bdab8f206967c22c8dfd7771"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v6.3.2+1/PROJ.v6.3.2.i686-linux-musl-cxx03.tar.gz"
