[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ccef46c4a5a535a54cb12fe1bc1bcec4bd39744"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "3e0afdb4f1e1a259693dc446881c67374bf9365cdfe438ff25bf12e243db1478"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bdf0e9f0c6fe0c14c07ba1e08b89047fb5b76b6"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f08f50ddbf2f32852bb32a4760ecfd41ca523d3fc72d3398779c10c31323ed9e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8e4be623313c03310323227e4fe1e39c222696b"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "9f379d334f93ca30a1501c2f701d6f1d5a4edc781471e0a681702f5f3b3f17d1"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ff6feb9234a4584dbdb04c7df64425d67e7a3d9"
os = "windows"

    [[PROJ.download]]
    sha256 = "02b8310e2acbc832385a7d82da95dfdffe4a89ca4ca48bf937d3c7110a356aef"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8869048eb57e0c950b098c63582f9da822e1af12"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "7913cf244753671f82c1547280b62800d3ab4b8ed018cf6090d27306e8c83b2b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "228ed2c29734bb68888b5e4f0b4eeabc2ae0e5da"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8e4c5021af1213a55f25c9917e31ef9c9495a4a9e031ac0aa6045e56bf9734af"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f85b44c4c37ca7deb95e090aca816a98c86f65f0"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "376752948326533091f13b439ccf684edfbd57ad5c07d1229ed816f5e1141bc7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72ee309def7fe1a38ba19b90ffeb47bb8d32b880"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d824747cfb1079b90f9473e2a37dc1125dac4cb8f68a9b25a067d4ad71c7e2e7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d5cfc45abeeb82a46f4382df6ec24d9d5c8841b"
os = "macos"

    [[PROJ.download]]
    sha256 = "65a0cc996d149076964abfb7f69072aef959463bf54b49f454934c065673c5a3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "975e72b783f7d92d68921531901e9e4bed57034b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9086f7bbed4553902f40a6e1777ac7b6a4f6bfc6c9d39cd17486308f59acf56e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "315f7c93d9100756d93cc8a93fb8415fdd39a377"
os = "windows"

    [[PROJ.download]]
    sha256 = "0e319adede4dc43b10cc128cdf26932be67b2d86b5f48c7845528c1cbec7b434"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ebc1f36eb673ea4e26039941640229558a113bb"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "54195b85badf5aa75a19f9fec612affdc2333b53cb0ba1329f831d0d4ea8b00b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cfe1015d1c40549953318d4cd84072b2064403b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "7c6d74976dac71653d0ac45cd209400b0c7abb4911e25b90eae2c2954def04c6"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97a11009119298b0223193bfc22a1b710b02041e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6dc093fc0edfd3613ee319eed1f467c47d94fa18fe45796735f0d5161ef45b90"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e984c8cf059ffed50a63f4b2f92dd7121a3b41c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8ec9dd811af748660001abe16ff1168df950e3769413a38746ece330e592630c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b457851f9a5ec14fd78f6834a9cfafe70a3acbe9"
os = "macos"

    [[PROJ.download]]
    sha256 = "163d4fde19ab7e541af8fbd39f5483cfa546f4b8b759bd87df8b539080877b33"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "addd4a68bd58ca3cfd555399de2d4060768c22f4"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "5b2de8da9e25da70ed771c6faafb9af081a0125e2d44c8852c2eb223034f880c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5b1e8008900c4a829cb64281e8b1b2a7fd2b841"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "59d205435a6c43ef3143c1ff037574f0f7560d8b2375e49817bd535f23e3b83e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87172f7c924cab3e617229f58341b2c15ffeec75"
os = "windows"

    [[PROJ.download]]
    sha256 = "fb30c988ad74fe7d26a0af4cbb1f6717a66da76e34ace629b8a917337d6b879e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b54905aa81c4d1da04fd800bfc9fc14c01c663"
os = "windows"

    [[PROJ.download]]
    sha256 = "144a302f83c6d4640296a594935f017355b32740d07d71aa4b0d709c933139f7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a5358371f059fd742f28792c13bd787c969f566"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "6a7d77521ea6f01009fe3df3170559842fbb6c8e50aefcc25ffb93d4132e3e33"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33bb0e63db863aaf8d168e39843c17c715f33079"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f6ed61d82b891c9fae6bffb0a6574e2d81436a54f19385f796f60fcd2294627b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e41ddd284c5e16ea71e49cca7dca387a711cf61b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e42441937d42f5dcad826dc53834a5be0dc8c779d5f80e03c4f12ba9a80d5911"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db60ad7295dc075ef048466d80d7d2cc23265887"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "2193f566aaf131cb2637265a7b86c5cbae4e0141f95a1fcf1d67c74d34c09415"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78dfa7bc0be6bfbd02504a27929c0a4fdcf7e75b"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "056ace55ce6f3e00423bafd55be98eb3fff7177599bc06217c9d960508c1122c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec4aec66f898705c387c17c813166ea08ef3c4eb"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "b482053b6d5ba05278a9c756b988c74c73543fd835dd616bfbc9a3d016e90082"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v7.0.1+0/PROJ.v7.0.1.i686-linux-musl-cxx03.tar.gz"
