[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "b05b1a49dfa2a2297925ab7dacfb21a9f5b985c4"
os = "macos"

    [[PROJ.download]]
    sha256 = "5c27818afdf54771c75ed1855f2c87588db176b103c547969059b541fc247de5"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e10dcc8cf609793bccae4bba623fbb8e2075477c"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6637e44315af3c3c0e946861a6cd24c0500a371aa28ef8a8e5b5642dcd658758"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0724f70cc557aa208fbe1e3f12e16fac5fadb544"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "6c317ca3d616c796a16b93b86cc210aa9a5c3cd11261b82fb42cc071b6a038f0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e3242fbc8f0f599bfeafd0f09e93a9b444760a8"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "121f116db0be2f06fe1bba3b460213d2434e1e2337111c18d4c88ed82bc53898"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6cc4fb8cf43a4e68fe46ba05e4dce9e58d7f693"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "0c78f1d37a6d317057cc15253760ef7653273de3e05bd3d134b478ea461129b4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d8fecace91146a21e2bc96825d34fc0f902b818"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "c699f3d988ad4ee53ddaa720d3c82eef99892e819187c9fe4c1c3c7d77e854f0"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f96687a4023f33c99d502cfbd6c0d8ea072fe2b8"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d82de98b7512656e030516e050bda0265384fa7c9cac90b7d665281803ff2e43"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35c584e78c79def2bc0e7c32532e3955a28994db"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "d0f163f09127903e5df64ad6121f036f4b0ced55e88c70c6bcb183909beabb75"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78a7c2b1ac94061022b6532e9e1ff445df2dee4c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "5c49b9c96b3c3aba432f530f860173c5c16d0cd6c604d82a21d3b336d9fa8d9e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4976ed2adf5a1a25772489a364bf7e74d6bd73a5"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "e3182301956f689effb375485fc4a2ba58d6a9e1ea9e2da49197dca0b4a595eb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68ef9db2419f3e7804257d01de5cdb72061b7fbf"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "4458082503fc0a9cc2bbd445dda2c4a131d1fdd64ea0dfd295407eeeb3962133"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e06a846a08a0d7a32ed9db54518b26e55fd38e5"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f110cadaf714483fbba5e0dd258491bb578f0cf1520ba27dd392c9ab71d5fc04"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e73c4b3996ce3eaf7983af2cae7d68dce2283b24"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "f1880b226e744d7db5c2e5a72f36d84761cdeb37326671f85c613c0159c7bc2c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a600c1f4717d077f02cac863bedeecc10b72c62"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "874d5f869e199cf20c81b9e61e2fd074d73a759f15cc2db07743af9f4eb39089"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0f1fb49fd32282b74a52b9ddc45e1b5d37fb9f1"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f53a9980b462de029dcbb52d6ad4c5cf1709ec992c8ef57dc9da8b22cb40ec29"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1df8431b29ec27e91306979a96b37ed42459b903"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "4690119b48eb423e3be8867bb66c9c87319cac30cb95327f57269b8d3ddb0448"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37c4cc1e7d547bb911bdf2cdc8f77e966bc88924"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "51f3daf055e04f2c7cca4c6014e658783ccebf8a71b3870a3610e0363a3e3507"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ce7954bcc95f5033e6824b93e21d9869679952b"
os = "windows"

    [[PROJ.download]]
    sha256 = "80cbeee4c4a587da7fadd5505c5f54f9f385bcdfd22c3e21971b6cd9eabbca95"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ddbf2138642a7ebe3e08554ff9a83cd99b4e97a"
os = "windows"

    [[PROJ.download]]
    sha256 = "39d3ca5de731df7e030c9a7650d36a546a40d0f7c1214b4c8058d069893c7b78"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b603b67cde66a2592be12072ef3f6fbdc36895"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "20ba91401f6e13bd586c9ebc7612db9c52b87abf7c2d7affa4ee2efc4c52c7b3"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff69de2b2763cd1b534ea4f8e9893ed1769aabe"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "be5a207059a4d68b8877be2a3745f9a82d418f1cc852c6817e8d9a313c38de10"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "926a44e5101cd0b7d25112cc2e18f9656db0ff00"
os = "macos"

    [[PROJ.download]]
    sha256 = "f3875c90e9aecf8b31a228d828124ee165faaf5d57ecc8614e5e209106769dc9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66079d041a907cd131573c2b2f69f7e01b01e415"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "83b3fc58a3e0e3db3f06a90cb24dcfb7bab621cc721eb343ed196ab79e6a8dcb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6484c8bfd53707477fa8178bcf7a19b0720d1bdb"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "9c44e1730ccc0a8fa239a6a4d77da59f0c6b98be440382431f7f3e847bb48bca"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9dce93cb75dee0956b8887c418b2fade00bac08"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "9baa06963edc0ef35178882db7072215604a834b7c4bfb98e7198e88503bce45"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65cc6bb84e7d6cc97a3880279d855ff14388dd07"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "a096e9e84937bdc54c39ea944918f2ad5ad4f90b0018f4990d185d3365ffd24d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "695125834bdcb16031a90bbe91fa147b9e1fa39d"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "9ebf70de756dfdd5b3ea336984c21a69d5f88f33f47ef1c110ecbd8beb1dd093"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72c1cc00bad3b05b5eea8997fe3e9a5c055ce830"
os = "windows"

    [[PROJ.download]]
    sha256 = "7938ca10700a660782b6361417cf3236aa53156ac8b5fed1f22e91fb2efd26f4"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6272043adc6bfd181a5fd19467130f726702dbc6"
os = "windows"

    [[PROJ.download]]
    sha256 = "57ad5dd72f14c72cfcfed5935e6ac9157c32f26141cc56f56861440f80a6c3b9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.0+0/PROJ.v800.200.0.x86_64-w64-mingw32-cxx11.tar.gz"
