[[PROJ]]
arch = "aarch64"
git-tree-sha1 = "4494a2d289af8f6ef124ba13cd90782ad1cf3008"
os = "macos"

    [[PROJ.download]]
    sha256 = "a0b067e6696e36ba7331d7cb16873381e03ebfcbec639e1ea6ee6deb69c0ee2b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.aarch64-apple-darwin.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a012d2d64767ba8d2e1398f87d77d09207ae5b7"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "d20c0d7987ca3f0a27fbe68ffeb82f81ca8f63c2efa1f8eed6e5ca36dc4b7c2d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.aarch64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b108714f8cceb7e20620046bf5467eed3c00663"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "db94842da77eb718c06d411c4b5e18ef11403634714ecd9c305f7748bf45417d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.aarch64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39f931c5725eb0e55e38e11c4e2bc45d057517a5"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "869dc64f63681700c3797e19c528811f61b98a13331d15a34ff7cd493c1ec269"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.aarch64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "561cfadfaf145340d48a94216ac5d9d5f9307b49"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "18df48cfe4b437687d8ffcecadd0e719f6278a86e3e84b00afcb3cc7d4890505"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.aarch64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d9c2a3af4e6a2419069f5f7719e45ae5b78df3d"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "da841dc875b74197d40b4bfc21bf3b10a887b9178ff2eeff5a01061871466cab"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e03c79d6ce38d36ed7af14157cc767b250187e58"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "a2dc045d9f1066415add718bae68454d51db48873fb3bd66419654f71a2e1b9f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fe0581ec95047eefd684dcfc5fa7e07691cd14c"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "143e0284facd8387e416a1fca989fd3231466c87a712633e912de4c174908384"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a34908b9baeb46c28aed3c6ba27f2cfae547bde1"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "35dce589cfd2cbbe21dab5379b67e69ab88421ae604d38a7165949c3e3292dd8"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce8dd4b3f8b3983069d283ee4eb37f94fc7055cb"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "82c5a887fa594a1a4b359058253b8cf95c8edb436f0bb5ceb5412acf7a53b343"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c68c94e6885a517f34cd9a2319e05d25c7674673"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "93002f6dba6fc66f2b4b4fa26bca83804d8d784d5a89abef3eae054aa22d406d"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "983dcbf4c3cd49867a61f763ea23b6673e90be1f"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "8aeb020a10fd6f1cb12dde0a96b687eac0b10bd07919b5a5953a5e7c3ad19e86"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PROJ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a599fe2fa0cb200cddad10df27738583396b132"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "1cec6c4dca0051d91af1f70a9d1ea54daa4cdb87918b531e3095b4d79a46a848"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7e4090e1327254a742040061feda5428fcc52ba"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "444fa3d8d6ea59803d8b21d23576fdde114702d0b9c12ee0c23fdbbcff883b98"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80670c2bdde71128451ce9cec973f6c94a18a37e"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "5739c36817b0d2e569c38bff2e97c5856faea5058cfd17626a0d88961407dbbb"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69127855160b7056cd3c34cbf7d444fb35416fee"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "db82251db5a68f9dc8c1e9ab6089c724f1d2ce290a63d11e2709e2813bafb957"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cb4c13d832df5eeac7f64ac97e2a3121d88ad26"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "ebb74bee76f646abe01657cfa7146bc6e45f44daaf6ded86282278d06665f73b"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "937223bf71e86f4473131759b4f0dc231d7a03f2"
os = "windows"

    [[PROJ.download]]
    sha256 = "2ddb6743bf1f59f232a15ccacee046b9ab8edd7b0c112f1741e9b8b84be5979c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08604187596e837ad42e78f7241acda85955e8ed"
os = "windows"

    [[PROJ.download]]
    sha256 = "a36458b9f09605bec02cd2382829f0ca2562fb9a84860931d074f9ecc9988d6c"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.i686-w64-mingw32-cxx11.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84a8e4683944d83b3b92169bfa5bb33454ccdcf3"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "8e542385e32ce81cb949e3619aa67f644fd7ffa8a58babfb5792f8abdc28b8f7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0654566a22b3edfd0452ad31d179a905fc8d165b"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "f5a42e3f85d3eb6d6b1e2c7737f9a2a444d19dd2778b580bf852da752913a072"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "bbbc9628a0d3d50c0295da474b6c09f2fb1712d4"
os = "macos"

    [[PROJ.download]]
    sha256 = "d006ab2a31264c2b633df66977a0063158bf23cde6f85975cfca2269fa143df7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-apple-darwin.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02cea5ecd533849c8439ad022149b29aab1d22f2"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "da3b6f088f922c599ff04bfe942337479c614fe1195e616004874840d7afe38f"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-linux-gnu-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "988c12a104f039161fb0940859dee220db5b7290"
libc = "glibc"
os = "linux"

    [[PROJ.download]]
    sha256 = "67072b899a95e0b3aecbf68fd72d105933b0b3af7ed4af0b02e4afa4031d2059"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-linux-gnu-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fc4a51fe1022fe7aa51042de7c07d7790b5cabf"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "5f52a9e27026aa3519687ec693fe466d63297d4f060b3aaf42844300e378d1dc"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-linux-musl-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf430b68967bccb02cd089a73ebd6e2153ea312d"
libc = "musl"
os = "linux"

    [[PROJ.download]]
    sha256 = "c806a3cd77cfa0ea70bb476246d7af071dafe76d6d12d174121fa81a8933bad9"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-linux-musl-cxx11.tar.gz"
[[PROJ]]
arch = "x86_64"
git-tree-sha1 = "089372c1ad810ed2f938ec6746e23f3aba29f9b9"
os = "freebsd"

    [[PROJ.download]]
    sha256 = "c0e55554694f68f60be339253c7e12fdb58bf1e73b78cc5b873e6a0304aae160"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-unknown-freebsd.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3bc77c064bf65de33d138a50d8f23d92c2a5591"
os = "windows"

    [[PROJ.download]]
    sha256 = "d972455f64f4e3fb064f9876a71ceb91b6cd54e2474046496abe4f9a4340937e"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-w64-mingw32-cxx03.tar.gz"
[[PROJ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d595b37c6d20ebc84ef0a98bd14267586f156424"
os = "windows"

    [[PROJ.download]]
    sha256 = "0be6dcfae046d977006cec7b70e9b621622d4031075587776ae89d90674fccb7"
    url = "https://github.com/JuliaBinaryWrappers/PROJ_jll.jl/releases/download/PROJ-v800.200.100+0/PROJ.v800.200.100.x86_64-w64-mingw32-cxx11.tar.gz"
